State Aggregation Function
multinet-app/multimatrix pull request #110
Opened 2020-10-16 15:42 UTC by mozartfish

This PR attempts to create a supernode graph for a small adjacency matrix

2020-10-16 17:53 UTC, waxlamp commented on src/components/Controls.vue
> + */
Just as a general matter of style, we use `// ` prefixed lines even for comment blocks like this.

2020-10-16 17:59 UTC, waxlamp commented on src/components/Controls.vue
> +  });
I don't think this is right: this just converts all California nodes to have the same key and ID, rather than creating a supernode that represents all such nodes.

2020-10-16 17:59 UTC, waxlamp commented on src/components/Controls.vue
> +        nodeNeighbors[i] === 'nodes/OAK'
Why not check to see if the state of the airport is California?

2020-10-16 17:59 UTC, waxlamp commented on src/components/Controls.vue
> +  const newNodes = otherNodes.concat(californiaNodes);
This isn't quite the approach you should take. You have in-place modified the original data, and then you've made a copy. I believe a better approach would be to perform a `forEach()` over the original nodes, and generate supernodes as needed to refer to the original nodes. Then you'll have both the (unmodified) original nodes, and a new list of supernodes. You will want to use a name like "supernodes" for the nodes in this new list. Finally, you'll want to do an `edges.forEach()` (as you did in line 61ff. above), but generate new edges there as well. You should under no circumstances be modifying the original data.

Once you have a list of supernodes and a list of new edges, you will have what you need for a transformed graph.

This is fairly complex and I may not have explained it well so we should meet in person to discuss it. @gotdairyya should be there as well.

2020-10-19 14:58 UTC, waxlamp reviewed
This is great progress, @mozartfish! I think we may need to talk about how to improve this further. But it's a great milestone that this actually works end-to-end within the application.

2020-10-19 14:58 UTC, waxlamp commented on src/components/Controls.vue
> +    newNodes.push(newNode);
There's an easier way to express this in ES6. It will be something like:

```typescript
const newNode = Object.assign({}, node, {
  parent: undefined,
});
```

Even better is the spread operator:

```typescript
const newNode = {
  ...node,
  parent: undefined,
};
```

You may want to read some documentation and experiment with these forms to make sure they work the way you expect.

2020-10-19 14:58 UTC, waxlamp commented on src/components/Controls.vue
> +    newNodes.push(newNode);
Some more comments about the code itself.

1. What is the purpose of the `parent` property?
2. You may not want to copy over the `_key` and `_id` fields exactly. If you wanted to push the new nodes list back to Multinet, you'd end up causing a problem, since nodes with those ID values already exist in the database. In general, I don't think it's necessary to copy every node like this; instead, you can simply reuse the original nodes in specifying the new network. It may require a meeting to discuss this, because it's sort of an area we have not explored too much yet.

2020-10-19 14:58 UTC, waxlamp commented on src/components/Controls.vue
> +      node['ORIGIN_STATE'] === 'California'
Any time you are referencing a JS object's properties statically like this, it's preferred to write it as `node._id` or `node.ORIGIN_STATE`, etc.

2020-10-19 14:58 UTC, waxlamp commented on src/components/Controls.vue
> +      newNodes[superIndex]['children'].push(node['index']);
Instead of recording the index in the children list, you should record the child node's ID. This will be unique within a Multinet instance, and is the canonical way to reference other nodes/edges in the system.

2020-10-19 14:58 UTC, waxlamp commented on src/components/Controls.vue
> +    newLinks.push(newLink);
Use `Object.assign()` or (better) the spread operator here, as mentioned above.

2020-10-19 14:58 UTC, waxlamp commented on src/components/Controls.vue
> +      link['_from'] = newLinkFrom;
The `_from` and `_to` properties MUST be ArangoDB ID values, NOT index values. This is a similar comment as above, but in some sense more important here, since ArangoDB (and thus Multinet) uses these fields to perform graph-based searches, etc.

2020-10-19 14:58 UTC, waxlamp commented on src/components/Controls.vue
> +  for (let index = 0; index < newLinks.length; index++) {
Rather than a for loop, you should use `Array.forEach()`. The second argument to `forEach()` is the index of each item. So basically, it's something like:

```typescript
newLinks.forEach((link, index) => {
  .
  .
  .
});
```

2020-10-19 14:58 UTC, waxlamp commented on src/components/Controls.vue
> +    const edgeName = 'edges/' + index;
Use a template literal here:

```suggestion
    const edgeName = `edges/${index}`;
```

2020-10-21 13:10 UTC, waxlamp reviewed
I think this is looking pretty good, @pranav! This branch has become rather messy because of a few factors, so let's spend some effort in cleaning it up (and perhaps rebasing the commits) and then I believe it will be ready for a final review and merge.

As part of that review, I think we'll have uncovered some problems with the architecture of the main application. If we make a note of these, we can fix those problems in follow-up PRs. (The main problem is, I believe, that the application mutates the input data in place to prep it for D3, and never expects that input data to change. I'm picturing more of a pipeline built around computed props, etc., that would allow the input data to change with minimal disruption to the D3 portion of the app. We'll need to discuss this a bit before we know what to do. cc @JackWilb)

2020-10-22 16:53 UTC, JackWilb requested changes
I noticed lots of dead code that should be removed, which made reviewing the logic a little tricky. I pointed out a couple of logic issues, but once you've cleaned them up, I'd like to take another pass over it.

2020-10-22 16:53 UTC, JackWilb commented on src/lib/multinet.ts
> +// keep the _from and _to fields to make it easier to folllow the multinet data format
Remove line 39

2020-10-22 16:53 UTC, JackWilb commented on src/lib/multinet.ts
> +    // delete row._to;
Delete these

2020-10-22 16:53 UTC, JackWilb commented on src/lib/multinet.ts
> +
Since this is the exact same logic as above, you can remove this and use the other function. You'll just want to export the function above and remove the `_` from the front

2020-10-22 16:53 UTC, JackWilb commented on src/lib/multinet.ts
> -
Was this a linter suggestion? Otherwise, we can leave the line there

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +import { loadData, defineSuperNeighbors } from '@/lib/multinet';
Once you remove this function in favor of `defineNeighbors`, you'll want to update the import here

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +// import { View } from './AdjMatrix/AdjMatrixMethods';
Looks like this remnant can be removed

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +
Can be removed

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +    delete newNode._rev;
This is an Arango field and can likely be removed on import. Thoughts @waxlamp

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +  const superNodes: any[] = [
We could either make this type `Node[]` or we could add a new type, `SuperNode`, which would extend `Node` with the additional children property.

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +  });
Do we need to specify the index? The Objects never move in the Array

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +  // console.log(superNodes);
Please remove

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +    // console.log(newLink);
Please remove

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +    delete newLink._rev;
This could also be removed on data loading, instead of here. See above

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +  // console.log(newLinks);
Please remove

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +  // console.log(newLinks);
Please remove

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +  // console.log(combinedNodes);
Please remove

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +  // console.log(neighborNodes);
Please remove

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +      // // console.log(superNetwork);
Please remove

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +    // console.log(newNode)
Please remove

2020-10-22 16:53 UTC, JackWilb commented on src/components/Controls.vue
> +  const finalNodes = neighborNodes.filter((node) => node.neighbors.length != 0);
This looks like it could be a bug. There could be nodes that have no neighbors before and after manipulation

2020-10-22 17:23 UTC, mozartfish commented on src/lib/multinet.ts
> +
This function needs to exist because if the _defineNeighbors d._id is changed to d.id, the visualization breaks. The reason is that when the data is originally uploaded by the user the id is represented with d._id. By the time the super node aggregation occurs, the id has already been converted from d._id to d.id using the data processing functions that are executed before the visualization is first rendered.

2020-10-22 17:44 UTC, waxlamp requested changes
Looking good, @mozartfish. Check out Jack's and my suggestions, and involve us if anything is unclear or if you want to discuss any of our feedback.

2020-10-22 17:44 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrix.vue
> +      // this.visDimensions.height = this.browser.height - 24;
Agreed.

2020-10-22 17:44 UTC, waxlamp commented on src/components/Controls.vue
> +    delete newNode._rev;
I agree. We could also just ignore it.

2020-10-22 17:44 UTC, waxlamp commented on src/components/Controls.vue
> +  const superNodes: any[] = [
I think `Node[]` is more appropriate at the moment. We'll have to think about whether we want to canonize supernodes as a specific type.

2020-10-22 17:44 UTC, waxlamp commented on src/components/Controls.vue
> +  });
This depends very much on why we need the index present. If it's for rendering the matrix, we need to figure out how to make sure the logic of computing the index is encapsulated to the rendering process.

Thoughts, @JackWilb and @mozartfish?

2020-10-22 17:44 UTC, waxlamp commented on src/components/Controls.vue
> +      superNode.ORIGIN.push(node.id);
I don't think this is correct, mainly because the data type will now vary based on whether this is a node or a supernode. Maybe that's unavoidable. But it makes thinking about the types involved a lot harder, so that makes me want to re-evaluate how we do this.

2020-10-22 17:44 UTC, waxlamp commented on src/components/Controls.vue
> +    newLink.index = `edges/${index}`;
The comment seems to disagree with the line of code. This looks more like an ID value to me, but it's drawing from an index value. I think we need a better sense for what the semantics of all these attributes is supposed to be.

2020-10-22 17:44 UTC, waxlamp commented on src/components/Controls.vue
> +  });
This is still very confusing.

I think it's probably fine for now, but we need to rearchitect how data flows through the system. I think the component should track the original data from Multinet, and use a computed prop to compute what is needed for D3. Then, this function wouldn't have to transform data from Multinet format to D3 format here and now; it could instead do the Multinet-to-Multinet transform, and let the component handle the conversion to D3.

Does this make sense @JackWilb?

2020-10-22 17:44 UTC, waxlamp commented on src/components/Controls.vue
> +  const finalNodes = neighborNodes.filter((node) => node.neighbors.length != 0);
The real thing to do is to go through the supernodes' children lists, and remove those nodes from `neighborNodes` (I think).

2020-10-22 17:44 UTC, waxlamp commented on src/components/Controls.vue
> +    clickButton(this: any) {
This should really be called "aggregateCalifornia" or something like that.

2020-10-22 17:44 UTC, waxlamp commented on src/components/Controls.vue
> +      this.network = superNetwork;
A general note about comments: you shouldn't self-describe the "obvious" parts of what the code is doing. In this case, you don't need to say you're calling a function and assigning to a variable. I'd simplify things like this:

```suggestion
      // Compute a new graph based on aggregating California airports into a supernode.
      this.network = superGraph(this.network.nodes, this.network.links);
```

2020-10-22 17:44 UTC, waxlamp commented on src/components/Controls.vue
> +          <!--button for aggregating by california -->
Another example: note that this comment doesn't add anything that's not self-evident from the code.

```suggestion
```

2020-10-22 17:44 UTC, waxlamp commented on src/lib/multinet.ts
> -
I doubt this was from the linter. I'd leave the line here (in the interest of both using whitespace for readability, and not making code changes unrelated to the PR).

2020-10-22 17:44 UTC, waxlamp commented on src/lib/multinet.ts
> +export function _renameLinkVars(links: any[]): Link[] {
If this is to be a public function, then remove the underscore.

2020-10-22 17:44 UTC, waxlamp commented on src/lib/multinet.ts
> +  for (const link of links) {
We should prefer `Array.forEach()` to `for..of` loops.

2020-10-22 17:44 UTC, waxlamp commented on src/lib/multinet.ts
> +}
I'm having some trouble understanding what this function does. The twin filter statements seem strange to me: they perform a filter on the full nodes array, then only operate on the first detected element. It seems inefficient, and the tight functional style obscures what this is trying to do.

2020-11-03 18:08 UTC, mozartfish commented on src/lib/multinet.ts
> +}
@JackWilb @waxlamp from my understanding of functional programming and what this function is doing (based on the original defineNeighbors) this function is identifying and creating the array of neighbor nodes for each node in the network. The reason why I had to create this function was that the data format changed between uploading the data and when the vis was first created before aggregation (the ._to, ._from). I think there might be cleaner way how to handle this since I found it slightly confusing to identify which parts needed to be kept for aggregation. Maybe we can clean up the defineNeighbors and defineSuperNeighbors in such a way where we don't have to duplicate code? I haven't found a solution for this though

2020-11-04 20:30 UTC, waxlamp commented on src/components/Controls.vue
> + */
This was fixed in an unknown commit.

2020-11-04 20:49 UTC, waxlamp commented on src/components/Controls.vue
> +import { loadData, defineSuperNeighbors } from '@/lib/multinet';
Opened #118 to track this, because for now we actually need to retain this function.

2020-11-04 21:11 UTC, waxlamp commented on src/lib/multinet.ts
> +    nodes.filter((d: Node) => d.id === link._to)[0].neighbors.push(link._from);
Use `.find()` instead of `.filter()` followed by `[0]`.

2020-11-04 21:12 UTC, waxlamp commented on src/lib/multinet.ts
> +    nodes.filter((d: Node) => d.id === link._to)[0].neighbors.push(link._from);
Opened #119 to track this.

2020-11-06 16:47 UTC, mozartfish commented on src/components/Controls.vue
> +      index: index,
fixed this issue. originally I thought you were referring to the parent so I changed the logic so we didn't need the parent but I just figured out now that index is not being used as I thought it was so it makes sense to remove this variable https://github.com/multinet-app/multimatrix/pull/110/commits/1cf25f3c37b26758d00fe36a7e4b73d3e665c40b

2020-11-06 16:54 UTC, mozartfish commented
@waxlamp @JackWilb according to this comment https://github.com/multinet-app/multimatrix/pull/110#discussion_r510333544, I found that the index is note needed for supernodes for updating the visualization so I removed the code in this commit https://github.com/multinet-app/multimatrix/pull/110/commits/8494c9dd316f56f2d41b5e3cc2e44c9cd201b051

2020-11-06 16:56 UTC, mozartfish commented
@waxlamp ran the linter and fixed the issue in this comment https://github.com/multinet-app/multimatrix/pull/110#discussion_r510342785

2020-11-10 01:32 UTC, mozartfish commented
This comment has been resolved https://github.com/multinet-app/multimatrix/pull/110#discussion_r510333544

2020-11-10 03:06 UTC, mozartfish commented on src/components/Controls.vue
> +    clickButton(this: any) {
resolved with this commit

2020-11-10 03:08 UTC, mozartfish commented on src/components/Controls.vue
> +// import { View } from './AdjMatrix/AdjMatrixMethods';
this issues has been resolved with commit https://github.com/multinet-app/multimatrix/pull/110/commits/0bf49564bff83f4af90ad6879c95f16998797c4a

2020-11-10 03:08 UTC, mozartfish commented on src/components/Controls.vue
> +  });
I commented on this issue recently

2020-11-10 03:09 UTC, mozartfish commented on src/lib/multinet.ts
> -
fixed the error with the linter by running yarn lint:fix

2020-11-10 03:09 UTC, mozartfish commented on src/components/Controls.vue
> +  const superNodes: any[] = [
I agree with Roni and I think this might happen when we get closer to finalizing the aggregation grouping functionality

2020-11-10 03:16 UTC, mozartfish commented on src/components/Controls.vue
> +    newLink.index = `edges/${index}`;
this has been resolved and the index has been removed

2020-11-10 21:15 UTC, waxlamp approved these changes

2020-11-10 23:01 UTC, JackWilb approved these changes

2020-11-11 02:23 UTC, merged