Attribute selection
multinet-app/multimatrix pull request #120
Opened 2020-11-11 04:01 UTC by mozartfish

This branch attempts to generalize aggregation by grouping for different attributes of the flight dataset.

2020-11-11 04:04 UTC, mozartfish commented
@waxlamp @JackWilb @gotdairyya I started this pull request for generalizing the aggregation by grouping similar to the state-aggr example but for all the states. For some reason I can't update the vis and the network prints out the right information (to my knowledge) so I was wondering if you guys might have an idea about why the vis might be failing. I update the vis in the adjmatrixmethods.ts file. 
Thanks

2020-11-11 17:05 UTC, waxlamp requested changes
Looks good overall; my comments are mainly style/typing/readability things.

One specific change not recorded below is, `AggMethods.ts` should not be capitalized. I would recommend changing the name of the file to `aggregation.ts`. You can do this by using `git mv`, but in the same commit where you make that change, be sure to also change all the import statements that make use of the file.

2020-11-11 17:05 UTC, waxlamp commented on src/lib/AggMethods.ts
> +  // console.log(newLinks);
```suggestion
```

2020-11-11 17:05 UTC, waxlamp commented on src/lib/AggMethods.ts
> +  newLinks.forEach((link: any) => {
Don't use `any` if possible.

2020-11-11 17:05 UTC, waxlamp commented on src/lib/AggMethods.ts
> +      superNode.CHILDREN.forEach((origin: any) => {
Don't use `any` if possible.

2020-11-11 17:05 UTC, waxlamp commented on src/lib/AggMethods.ts
> +  // console.log(newLinks)
```suggestion
```

2020-11-11 17:05 UTC, waxlamp commented on src/lib/AggMethods.ts
> +  // console.log(newLinks);
```suggestion
```

2020-11-11 17:05 UTC, waxlamp commented on src/lib/AggMethods.ts
> +  // console.log(neighborNodes);
```suggestion
```

2020-11-11 17:05 UTC, waxlamp commented on src/lib/AggMethods.ts
> +  // remove all the nodes who do not have any neighbors
Not sure this is correct. Some nodes may have been neighborless originally, and those shouldn't be removed, right?

2020-11-11 17:05 UTC, waxlamp commented on src/lib/AggMethods.ts
> +  // console.log(finalNodes);
```suggestion
```

2020-11-11 17:05 UTC, waxlamp commented on src/lib/AggMethods.ts
> +  return network;
```suggestion
  return {
    nodes: finalNodes,
    links: newLinks,
  };
```

2020-11-11 17:08 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    // .on('click', (d: string) => this.sort(d));
removed the unused code

2020-11-11 17:10 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +        return;
Removed the unused return

2020-11-11 17:13 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +        console.log('clicked the text label');
this commit is currently used for debugging and I plan to keep it in there until the vis can be updated. @JackWilb @waxlamp was there a reason why we have different click functionalities. I found that users can either click the widget icon or the text to do the same task but I'm thinking we only need one. Any thoughts on this?

2020-11-11 17:13 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    // .on('click', (d: string) => this.sort(d));
see comment here https://github.com/multinet-app/multimatrix/pull/120#discussion_r521510705

2020-11-11 17:14 UTC, mozartfish commented on src/components/Controls.vue
> +      // );
Removed blocks of commented out code

2020-11-11 17:15 UTC, mozartfish commented on src/lib/AggMethods.ts
> +  // console.log(newLinks);
Removed blocks of commented out code

2020-11-11 17:15 UTC, mozartfish commented on src/lib/AggMethods.ts
> +  // console.log(finalNodes);
Keeping this in for debugging the vis. The PR I submitted is a draft PR since I can't find a bug that involves updating the vis

2020-11-11 17:16 UTC, mozartfish commented on src/lib/AggMethods.ts
> +  return network;
Keeping this for now for debugging the vis. Once the vis works, I will remove this code

2020-11-11 18:32 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +export function superGraph(nodes: any[], edges: any[], attribute: string) {
Created new issue to address this #122 

@waxlamp is it alright to address to resolve and address issue later?

2020-11-11 18:35 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +  });
@waxlamp ok to change later?

made new issue #124

2020-11-11 18:35 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +  selectedAttributes.forEach((attr) => {
See #124

2020-11-11 18:37 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +      const superNode = superNodes.find(
Opened issue #125 

Let's come back to this later 

@waxlamp is that alright?

2020-11-11 18:37 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +  edges.forEach((link) => {
#124

2020-11-11 18:38 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +  newLinks.forEach((link: any) => {
#123

2020-11-11 18:38 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +      superNode.CHILDREN.forEach((origin: any) => {
#123

2020-11-11 18:39 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +  // remove all the nodes who do not have any neighbors
Yeah, I think that this could be a problem

2020-11-11 18:39 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +export function superGraph(nodes: any[], edges: any[], attribute: string) {
#123

2020-11-11 18:39 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +  });
Issue #124

2020-11-11 18:40 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +  selectedAttributes.forEach((attr) => {
Issue #124

2020-11-11 18:41 UTC, gotdairyya commented on src/lib/AggMethods.ts
> +      _key: attr,
Issue #125 

@waxlamp if this works currently, could we address this later?

2020-11-11 19:14 UTC, waxlamp commented on src/lib/AggMethods.ts
> +  // console.log(finalNodes);
If you need to debug the vis you can insert these statements as needed. I don't like adding commented-out code in one PR because it will be hard to spot in the future.

Let me know if you think you can get rid of these commented out blocks now and re-insert them as needed when you are actually debugging.

2020-11-11 19:17 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +        console.log('clicked the text label');
One thing you can do is leave these commented block in your code, and just not check them into a PR. Then you have them locally but they don't get submitted for review, etc. I am strongly against checking in commented out code, as it creates a danger of a messy codebase in the future.

2020-11-11 19:18 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    // .on('click', (d: string) => this.sort(d));
But why did you change the behavior of the old handler here?

2020-11-11 19:20 UTC, waxlamp commented on src/lib/AggMethods.ts
> +      _key: attr,
Yes, but this one is pretty critical to fix sooner rather than later (it will cause serious slowdowns for even moderately large datasets).

2020-11-18 17:04 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    // .on('click', (d: string) => this.sort(d));
@waxlamp this comment has been fixed and the console.log is now removed.

2020-11-18 17:05 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    // .on('click', (d: string) => this.sort(d));
@waxlamp removed the unused handler as requested

2020-11-19 19:14 UTC, mozartfish commented on src/lib/AggMethods.ts
> +  // remove all the nodes who do not have any neighbors
@waxlamp @gotdairyya filed an issue about this https://github.com/multinet-app/multimatrix/issues/128#issue-746852126

2020-11-19 19:17 UTC, mozartfish commented on src/lib/AggMethods.ts
> +  return network;
@waxlamp this request has been resolved with this commit https://github.com/multinet-app/multimatrix/pull/120/commits/04c4df4e4e73808151fdf8418cf81c05ebc7100e

2020-11-19 19:17 UTC, mozartfish commented on src/lib/AggMethods.ts
> +  // console.log(finalNodes);
@waxlamp this request has been resolved with this commit https://github.com/multinet-app/multimatrix/pull/120/commits/04c4df4e4e73808151fdf8418cf81c05ebc7100e

2020-11-19 19:18 UTC, mozartfish commented on src/lib/AggMethods.ts
> +  // console.log(neighborNodes);
this request has been resolved with this commit https://github.com/multinet-app/multimatrix/pull/120/commits/04c4df4e4e73808151fdf8418cf81c05ebc7100e

2020-11-20 20:58 UTC, waxlamp approved these changes

2020-11-21 01:01 UTC, JackWilb approved these changes
I don't want to hold back an approval, since this code is generally good to go. I just had a question for you regrading keeping the sorting. I think we can merge this, I just want to make sure we don't introduce a regression here that we're not tracking

2020-11-21 01:01 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .style('fill', '#8B8B8B');
We should consider keeping the sorting functionality for the attributes. Is there a way we can have the superGraph trigger and have the sorting? This could be an issue that you open for me to investigate

2020-11-21 01:48 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .style('fill', '#8B8B8B');
@JackWilb I filed an issue about this since this is something I have discussed with Alex and Derya and something we hope to have possibly working potentially by May

2020-11-21 01:51 UTC, merged