Matrix animation
multinet-app/multimatrix pull request #130
Opened 2020-11-24 20:27 UTC by mozartfish

Added d3 transition to render the matrix smoothly

2020-11-24 20:42 UTC, waxlamp requested changes
This looks great! The biggest problem is that you have a lot of code in this PR that's meant for a different PR. I can help you straighten it all out.

2020-11-24 20:42 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +dom.watch();
Please move this code block to below the imports, and include a comment to explain why it's needed.

2020-11-24 20:42 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +  private clickBool: number;
This doesn't seem to be used anywhere in the PR.

2020-11-24 20:42 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    this.clickBool = 0;
See above.

2020-11-24 20:42 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      // addd a transition somewhere here? for the rows?
Remove this comment.

2020-11-24 20:42 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    const chevronHeight = 30;
The chevron stuff doesn't belong in this PR. I can help you to ensure that these commits are on your newer branch but not here.

2020-11-24 20:42 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +
See above about not putting chevron stuff into this PR.

2020-11-24 20:42 UTC, waxlamp commented on package.json
> +    "@fortawesome/free-solid-svg-icons": "^5.15.1",
If these are for drawing the chevrons, I believe we can move this commit along with the code changes adding the icons to your newer branch.

2020-11-26 17:58 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +dom.watch();
resolved with this commit https://github.com/multinet-app/multimatrix/pull/130/commits/8a80efa8f6f7eab931cef1dcde707dcfb368d0d2

2020-11-26 17:59 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    this.clickBool = 0;
resolved with this commit https://github.com/multinet-app/multimatrix/pull/130/commits/8045d5c9bedde82b6dd8b238ad29d803271571ea

2020-11-26 18:00 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      // addd a transition somewhere here? for the rows?
resolved with this commit https://github.com/multinet-app/multimatrix/pull/130/commits/bb81208312841db51914be8a21555fc62f10e87b

2020-11-26 18:01 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    const chevronHeight = 30;
resolved with this commit https://github.com/multinet-app/multimatrix/pull/130/commits/6cf0f1b07d79fc9499f991a9e88ea09b9a57bbac

2020-11-26 18:02 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +
see above about the changes to the chevron stuff in this PR https://github.com/multinet-app/multimatrix/pull/130#discussion_r531173876

2020-11-26 18:03 UTC, mozartfish commented on package.json
> +    "@fortawesome/free-solid-svg-icons": "^5.15.1",
I to clone multimatrix again since I accidentally deleted the folder while moving stuff around on my local machine. Luckily all my work was saved so the font awesome package stuff is not in this commit

2020-11-30 18:37 UTC, JackWilb requested changes
Looks like there is some work to do to clean this up still. I think 0.5 sec is too quick for the animation.

There may be some cases where we don't want to translate them all to 0,0 and then animate them to their final spot, (I'm thinking expanding children nodes). Have you thought at all about how to handle that @mozartfish?

2020-11-30 18:37 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    this.clickBool = 0;
This was not resolved in that commit @mozartfish

2020-11-30 18:37 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .duration(500)
Seems like half a second here is too quick

2020-11-30 18:40 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrix.vue
> +      visMargins: { left: 150, top: 75, right: 0, bottom: 0 },
Looks like 150 is a bit too much space here. Why did you update this value?

2020-11-30 19:03 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrix.vue
> +      visMargins: { left: 150, top: 75, right: 0, bottom: 0 },
@JackWilb I updated this value to make room for the chevrons. If the matrix wasn't translated then we would have to readjust the text labels changes I made earlier. @waxlamp @JackWilb I came up with these two plans and tried both. This PR uses idea 1. Do you have an opinion on which idea is a better solution in the long run? 

The two ideas I have for this are the following 
1) translate the matrix - this avoids resizing and repositioning the foreign object label changes I made earlier and makes room for the chevrons

2) modify the foreign object labels - resize and reposition all the labels and make sure they work for the flight aggr dataset and les mis. The issue with this idea is that we need to check every new dataset to make sure the labels are positioned correctly for both the previous working datasets and the new datasets. For example when I first made the changes to the labels, when I positioned the labels to work for the flight aggr vis, they didn't line up for les mis and vice versa. Eventually I found a value that worked for both.

2020-11-30 19:06 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .duration(500)
I'll try to experiment with different animation times.

2020-11-30 19:08 UTC, mozartfish commented
@JackWilb This branch is supposed to demonstrate animations for the matrix. I am currently working on another branch called interact-expand-supernode that plans to address your feedback

2020-11-30 19:12 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrix.vue
> +      visMargins: { left: 150, top: 75, right: 0, bottom: 0 },
I think translating the matrix is fine. However, it shouldn't be in this PR, since it's an unrelated changed. You should revert these changes and just include them in the PR that adds the chevrons

2020-11-30 19:36 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +  private clickBool: number;
8045d5c seems to address this.

2020-11-30 19:38 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +    this.clickBool = 0;
this issue is addressed with this commit https://github.com/multinet-app/multimatrix/pull/130/commits/2179c3812ead4272f827c7b35a858c53a4623758

2020-11-30 19:38 UTC, waxlamp commented on package.json
> +    "@fortawesome/free-solid-svg-icons": "^5.15.1",
Are you sure? These lines are still showing up on this branch.

2020-11-30 19:39 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrix.vue
> +      visMargins: { left: 150, top: 75, right: 0, bottom: 0 },
this issue is addressed with this commit https://github.com/multinet-app/multimatrix/pull/130/commits/fb2b8554720abe3c662e33d4e915505fbe554da1

2020-11-30 19:40 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrix.vue
> +      visMargins: { left: 150, top: 75, right: 0, bottom: 0 },
In general it won't be good enough to account for only two example datasets. As I've said in the past, you can and should reach out to Jared for help with this sort of thing; he can help you figure out the right way to accommodate the UI elements you need for all datasets.

For the moment I agree with Jack--since you're no longer adding chevrons in this PR, this change to the margins shouldn't be here.

2020-11-30 19:41 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .duration(500)
> I'll try to experiment with different animation times.

You can also ask Derya and Alex for some insight. To me, 500ms seems like it's in the right neighborhood.

@JackWilb, if it's ok with you, maybe we can defer the animation time to the supernodes PR--there it will be more of a critical value to get right.

2020-11-30 19:42 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> +      .duration(500)
this issue is addressed with this commit https://github.com/multinet-app/multimatrix/pull/130/commits/14043d356f89d7abe3ef63c6510c26842494d339

2020-11-30 19:44 UTC, waxlamp commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> -
Restore the blank line here.

2020-11-30 19:44 UTC, waxlamp requested changes
See the individual open threads for the change requests.

2020-11-30 19:46 UTC, mozartfish commented on package.json
> +    "@fortawesome/free-solid-svg-icons": "^5.15.1",
this issue is resolved with this commit https://github.com/multinet-app/multimatrix/pull/130/commits/45b4c7e2cb3a493f483d4631058352904058f127

2020-11-30 19:49 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrixMethods.ts
> -
this commit addresses this issue https://github.com/multinet-app/multimatrix/pull/130/commits/ec54645ff0c924e65b47726e342240aad60d2402

2020-11-30 20:09 UTC, JackWilb requested changes

2020-11-30 20:09 UTC, JackWilb commented on yarn.lock
> +
These changes shouldn't be here since there is no change to the package.json

2020-11-30 20:09 UTC, JackWilb commented on src/components/AdjMatrix/AdjMatrix.vue
> +      },
This change seems unrelated

2020-11-30 21:01 UTC, mozartfish commented on yarn.lock
> +
resolved with this commit https://github.com/multinet-app/multimatrix/pull/130/commits/4c8824135836ee7668c145c3d4e94e775558c68a

2020-11-30 22:51 UTC, mozartfish commented on src/components/AdjMatrix/AdjMatrix.vue
> +      },
resolved here with this commit https://github.com/multinet-app/multimatrix/pull/130/commits/d8144262d8b4a06fef57afe0da8a80a4d45ac120

2020-11-30 22:52 UTC, JackWilb approved these changes

2020-12-01 16:28 UTC, waxlamp approved these changes
I think the 1.1 second transition may be too long, but we can fine tune this in the followup work.

2020-12-01 16:40 UTC, merged