Restructured expand supernodes
multinet-app/multimatrix pull request #159
Opened 2020-12-21 18:42 UTC by mozartfish

PR for restructuring the expand supernodes so that the matrix will not re-render every time the user clicks on a chevron

2021-01-11 19:47 UTC, gotdairyya commented on src/lib/aggregation.ts
> +// function that creates a deep copy of links
can you make this one line
`// function that creates a deep copy of nodes + links`

2021-01-11 19:49 UTC, gotdairyya commented on src/lib/aggregation.ts
> +function deepCopyNodes(nodes: Node[]) {
how is this function different than the one above?

2021-01-11 19:51 UTC, gotdairyya commented on src/lib/aggregation.ts
> +
i would add a comment here too for safe measure about the function's purpose

2021-01-11 19:51 UTC, gotdairyya commented on src/lib/aggregation.ts
> +
here as well

2021-01-11 19:56 UTC, gotdairyya reviewed
I left some comments in `aggregation.ts` to increase the clarity of the methods

2021-01-11 19:57 UTC, mozartfish commented on src/lib/aggregation.ts
> +// function that creates a deep copy of links
resolved in this commit https://github.com/multinet-app/multimatrix/pull/159/commits/caf142518eff0221a811b4bafc24bc047167dce7

2021-01-12 00:53 UTC, mozartfish commented on src/lib/aggregation.ts
> +function deepCopyNodes(nodes: Node[]) {
resolved in this commit https://github.com/multinet-app/multimatrix/pull/159/commits/2a665a8b0a9f2786e69eb9663f9cc11e858667c9

2021-01-12 00:54 UTC, mozartfish commented on src/lib/aggregation.ts
> +
resolved in this commit https://github.com/multinet-app/multimatrix/pull/159/commits/2a665a8b0a9f2786e69eb9663f9cc11e858667c9

2021-01-12 00:54 UTC, mozartfish commented on src/lib/aggregation.ts
> +
resolved in this commit https://github.com/multinet-app/multimatrix/pull/159/commits/2a665a8b0a9f2786e69eb9663f9cc11e858667c9

2021-01-12 17:11 UTC, JackWilb requested changes
Looking good so far. You're well on your way. I've made a note of several things to remove and some general code style that needs to be updated. I imagine that once you've addressed these comments, I may have another round of changes for you to address.

2021-01-12 17:11 UTC, JackWilb commented on src/lib/aggregation.ts
> +  if (superNode != undefined) {
```suggestion
  if (superNode !== undefined) {
```

2021-01-12 17:11 UTC, JackWilb commented on src/lib/aggregation.ts
> +      if (childNode != undefined) {
Another != that should be !==, please update throughout the file

2021-01-12 17:11 UTC, JackWilb commented on src/lib/aggregation.ts
> +  if (retractNodes && retractLinks != undefined) {
```suggestion
  if (retractNodes !== undefined && retractLinks !== undefined) {
```

2021-01-12 17:11 UTC, JackWilb commented on src/lib/aggregation.ts
> +    });
Is this necessary?

2021-01-12 17:11 UTC, JackWilb commented on src/lib/aggregation.ts
> +  if (superNode != undefined) {
```suggestion
  if (superNode !== undefined) {
```

2021-01-12 17:11 UTC, JackWilb commented on src/lib/aggregation.ts
> +    });
Is this necessary?

2021-01-12 17:11 UTC, JackWilb commented on src/lib/aggregation.ts
> +      link.target = link._to;
It's not necessary to set target

2021-01-12 19:23 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +      expandRetractAggrVisLinks: undefined,
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/e20e94dbadb09cfa74774ac180c4735b482e75ca

2021-01-12 19:26 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +              if (this.clickMap.get(supernode.id) === true) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/353919866c99ff7f180018e9e5256b5269b12163

2021-01-12 19:37 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +    expandRetractAggrVisLinks: any; // variable for keeping track of the current links being visualized
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/2bf1fef1867ef5aacb34c965c2d477e94af708a8

2021-01-12 19:37 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +            this.clickMap = new Map<string, boolean>();
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/2bf1fef1867ef5aacb34c965c2d477e94af708a8

2021-01-12 19:42 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +            if (this.clickMap.has(supernode.id)) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/f9a21b3cea2d535cb88156836de46b318977b980

2021-01-12 19:45 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +
I'm not too sure about what to remove here

2021-01-12 19:49 UTC, mozartfish commented on src/lib/aggregation.ts
> +}
These functions assume that the type has already been set whereas `processChildNodes` and `processChildLinks` set up the types

2021-01-12 19:55 UTC, mozartfish commented on src/lib/aggregation.ts
> +  // Remove nodes who do not have neighbors
Refactored comments to maintain consistent comment style in the multimatrix app

2021-01-12 19:56 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +    },
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/c9c68c7577b2fa0c52b12943adb0969876cb88f6

2021-01-12 19:59 UTC, mozartfish commented on src/lib/aggregation.ts
> +          link.source = link._from;
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/815050801872c17a834e795bc9bf77b603dff01b

2021-01-12 20:00 UTC, mozartfish commented on src/lib/aggregation.ts
> +          link.target = link._to;
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/379fe200e3a928b9cf42e626c3223ea8f576e77e

2021-01-12 20:08 UTC, mozartfish commented on src/lib/aggregation.ts
> +    }
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/5650d177ef637872a0df539027bea38e822a30c7

2021-01-12 20:18 UTC, mozartfish commented on src/lib/aggregation.ts
> +      if (childNode != undefined) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/3752d680fd7cd444ade60fc68024b061652b2fcb

2021-01-12 20:18 UTC, mozartfish commented on src/lib/aggregation.ts
> +  if (superNode != undefined) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/3752d680fd7cd444ade60fc68024b061652b2fcb

2021-01-12 20:18 UTC, mozartfish commented on src/lib/aggregation.ts
> +  if (retractNodes && retractLinks != undefined) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/3752d680fd7cd444ade60fc68024b061652b2fcb

2021-01-12 20:20 UTC, mozartfish commented on src/lib/aggregation.ts
> +      (link: Link) => link.source !== childNode && link._from !== childNode,
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/1056a892893dc30f10b1a446b6c39dbd5ccb5c05

2021-01-12 20:21 UTC, mozartfish commented on src/lib/aggregation.ts
> +  if (expandNodes && expandLinks != undefined) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/b6269f6e238accbc36bad658b3baf03a54e05ba2

2021-01-12 20:21 UTC, mozartfish commented on src/lib/aggregation.ts
> +  if (superNode != undefined) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/aef22b844ca0c17ac70bef5dcb1bf2bfaf485e02

2021-01-12 20:22 UTC, mozartfish commented on src/lib/aggregation.ts
> +    });
I update all the indexes to keep track of where to index when adding and removing nodes for expanding and retracting the vis

2021-01-12 20:23 UTC, mozartfish commented on src/lib/aggregation.ts
> +    });
I update the index to keep track of where to insert and remove nodes and links when expanding and retracting the vis

2021-01-12 20:42 UTC, mozartfish commented on src/lib/aggregation.ts
> +      link.target = link._to;
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/d903d248f55ad0fe65ff104a0fd7e37ca2a57e77

2021-01-12 21:01 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/8b3bfa7c3e418e51998ff2878dd2dfbe6a146236

2021-01-12 22:10 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +
figured out a solution and resolved this issue with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/c97cb586b59bcd5dbdc85ea691f4075251f6693f

2021-01-12 22:19 UTC, mozartfish commented on src/lib/aggregation.ts
>    nodes.map((node) => {
this issue was discussed here https://github.com/multinet-app/multimatrix/issues/124

2021-01-13 01:51 UTC, JackWilb requested changes
Almost there, just a couple more comments to address and we can get it merged 💯

2021-01-13 01:51 UTC, JackWilb commented on src/lib/aggregation.ts
>    nodes.map((node) => {
Right, but you note that part of that change was to do
```
const newNodes: any[] = nodes.map((node) => {
```

and to do 

```
return newNode;
```

instead of pushing the `newNode`. You haven't quite solved the problem. Please reopen that issue. Link this comment and circle back to fix it.

I prefer the map to the forEach, too.

2021-01-13 01:51 UTC, JackWilb commented on src/lib/aggregation.ts
>    });
This would be another good spot for a map, please link this comment in #124

2021-01-13 01:51 UTC, JackWilb commented on src/lib/aggregation.ts
> +  // Remove nodes who do not have neighbors
Sorry, I should have highlighted more lines. Why do we have to remove the neighbors?

2021-01-13 01:51 UTC, JackWilb commented on src/lib/aggregation.ts
> +}
Gotcha. Do we need to do that though? Doesn't that happen when you call `superGraph` [here](https://github.com/multinet-app/multimatrix/pull/159/files#diff-34358225552a6eca72dcc40b648e49001e9ffa7444dc76900a80e24380ebe7a4R15)?

2021-01-13 01:51 UTC, JackWilb commented on src/lib/aggregation.ts
> +    });
Right, but does the index need to be on the node or can you just reference it when you loop through the array of nodes with `nodes.forEach((node: Node, index: number) => {})`? I'm asking, do we ever use the index without looping through the array?

2021-01-13 01:51 UTC, JackWilb commented on src/lib/aggregation.ts
> +    });
I"m going to leave this open and discuss in the other comment, just so we can keep track that this might need to be updated

2021-01-13 01:51 UTC, JackWilb commented on src/lib/aggregation.ts
> +    });
Also, it looks like you are using `id` not `index` to add and remove nodes. You don't use the index here:

```
 const superIndexFunc = (superNode: Node) => superNode.id == superNodeName;
    const superIndexStart = superNodeCopy.findIndex(superIndexFunc);
    let count = 1;
    childNodes.forEach((node) => {
      superNodeCopy.splice(superIndexStart + count, 0, node);
      count += 1;
    });
```

And it's similar on retracting the expanded superNode

2021-01-13 01:51 UTC, JackWilb commented on src/lib/aggregation.ts
> +    // in the correct position for visualizing the supergraph network
insert => remove

2021-01-13 01:51 UTC, JackWilb commented on src/lib/aggregation.ts
> +  if (retractNodes && retractLinks !== undefined) {
```suggestion
  if (retractNodes !== undefined && retractLinks !== undefined) {
```

2021-01-13 01:51 UTC, JackWilb commented on src/lib/aggregation.ts
> +    if (findNodeFrom && findNodeTo !== undefined) {
```suggestion
    if (findNodeFrom !== undefined && findNodeTo !== undefined) {
```

2021-01-13 02:13 UTC, mozartfish commented on src/lib/aggregation.ts
> +    if (findNodeFrom && findNodeTo !== undefined) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/796fd92fa34e8d4065aa682fce33da42eb73f308

2021-01-13 02:13 UTC, mozartfish commented on src/lib/aggregation.ts
> +  if (retractNodes && retractLinks !== undefined) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/3dc1052fb69764e7249d2f247c21d2115e0913cb

2021-01-13 02:53 UTC, mozartfish commented on src/lib/aggregation.ts
>    nodes.map((node) => {
resolved issue #124 with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/b4b1a942ae28dbd8361c35f0ed522fee0d9a9881

2021-01-13 02:59 UTC, mozartfish commented on src/lib/aggregation.ts
>    });
resolves issue #124 with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/4385b7ccec2e1b2fa56dba30c89b4730020a1870

2021-01-13 03:03 UTC, mozartfish commented on src/lib/aggregation.ts
> +    });
Removed the index code and the functionality of the PR did not change so I agree with removing this section of code. I addressed this issue with commit https://github.com/multinet-app/multimatrix/pull/159/commits/6383e7119fdb8b6d7e46900e74b942f1c1b8c722

2021-01-13 03:07 UTC, mozartfish commented on src/lib/aggregation.ts
> +    });
Tested the PR code by removing the index code and nothing broke so I agree with the comment to remove this code. This issue is addressed with commit https://github.com/multinet-app/multimatrix/pull/159/commits/7738a5eac4ed7a5412575bd6cebb1dfa0728a535

2021-01-13 03:12 UTC, mozartfish commented
Comment https://github.com/multinet-app/multimatrix/pull/159#discussion_r556205317
I had some problems with the matrix updating the nodes and links before I called expand and retract so I had to deep copy of the nodes and links to ensure they were not manipulated during the transitions and when the data was updated for the Vue component. @JackWilb @gotdairyya any suggestions for how to fix this without using deep copy? Thanks!

2021-01-13 03:15 UTC, mozartfish commented on src/lib/aggregation.ts
> +    // in the correct position for visualizing the supergraph network
resolved with this commit https://github.com/multinet-app/multimatrix/pull/159/commits/43fbd441e1c1fc6d88ed06a7a770cbb93556059d

2021-01-13 03:26 UTC, mozartfish commented
Comment https://github.com/multinet-app/multimatrix/pull/159#discussion_r556204568
When constructing new neighbor nodes, the non-aggregated nodes neighbors do not get updated. I remove these nodes so the network reflects the aggregated nodes. However, there is a potential issue with this such if there is a node in the network that is disconnected from all the other nodes in the graph. @gotdairyya @JackWilb any thoughts about this? I can file an issue about this for the future since it does not currently relate to this PR

2021-01-13 17:36 UTC, JackWilb commented on src/lib/aggregation.ts
> +  // Remove nodes who do not have neighbors
Discussed in person, #128

2021-01-13 17:44 UTC, JackWilb commented on src/lib/aggregation.ts
> +}
Talked in person, can refactor at a later date if necessary

2021-01-13 17:48 UTC, JackWilb approved these changes

2021-01-13 18:05 UTC, gotdairyya approved these changes

2021-01-13 18:42 UTC, merged

2021-01-13 18:51 UTC, waxlamp reviewed
The expand/collapse behavior looks good overall, though it's not quite right. I notice that on collapse, the data rows just disappear; it would be better if they animated away as they do on expansion. And, on expansion, the data rows flow in from the very top; they should flow in from the supernode position instead.

Finally, adding chevrons in the left margin will go a long way towards delineating what is a super node and what are the "regular" nodes.

@JackWilb, can you file issues to track these?

2021-01-13 19:02 UTC, JackWilb commented
> @JackWilb, can you file issues to track these?

Opened #180 + #181