Animating Rows - Fixes Issue #181
multinet-app/multimatrix pull request #188
Opened 2021-01-25 17:35 UTC by mozartfish

This PR addresses issue #181 by adding in new transitions for the row exit animation and replaces the fan animation with a fade.

2021-01-28 22:51 UTC, gotdairyya commented
1. Seems like there is a bug where when you try to "open" more than one row it doesn't work (this is a bug that sometimes occurs and sometimes doesn't, @JackWilb does this happen for you too?)
2. I'm not the biggest fan of the enter transitions (but this is not an important issue) I think it would be cleaner if the labels just occurred in place

2021-01-28 23:04 UTC, JackWilb commented
>     1. Seems like there is a bug where when you try to "open" more than one row it doesn't work (this is a bug that sometimes occurs and sometimes doesn't, @JackWilb does this happen for you too?)

I'm not seeing that behavior. Do you have a reproducible example? Can you share a video of it?

>     2. I'm not the biggest fan of the enter transitions (but this is not an important issue) I think it would be cleaner if the labels just occurred in place

Once we have the animation, it would be easy to decide what would be the best visually. We'll likely want input from Alex and Jared on this, so let's not worry to much about this for now. We could make an issue out of it, if you think it's a big deal

2021-01-28 23:10 UTC, JackWilb requested changes

2021-01-28 23:10 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +        .remove();
Neither the rows nor columns seem to actually animate out, they just pop. Is this code actually doing anything? Do you need to add similar code to more places for a better animation?

2021-01-28 23:10 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +        });
If we're going to do this for the rows, does it make sense to also do it for the columns? I'm just wondering how that would look overall

2021-01-28 23:10 UTC, JackWilb commented on src/lib/aggregation.ts
> +    });
Is this used anywhere? I don't think find index needs and index property on the objects

2021-01-28 23:10 UTC, JackWilb commented on src/lib/aggregation.ts
> +    });
Same as above

2021-01-28 23:12 UTC, JackWilb commented
This really breaks sorting, by the way. Please file an issue that we need to fix that

2021-01-28 23:25 UTC, gotdairyya commented
> > ```
> > 1. Seems like there is a bug where when you try to "open" more than one row it doesn't work (this is a bug that sometimes occurs and sometimes doesn't, @JackWilb does this happen for you too?)
> > ```
> 
> I'm not seeing that behavior. Do you have a reproducible example? Can you share a video of it?
> 
Tried to replicate and it is working fine now, not sure what happened there.
> > ```
> > 2. I'm not the biggest fan of the enter transitions (but this is not an important issue) I think it would be cleaner if the labels just occurred in place
> > ```
> 
> Once we have the animation, it would be easy to decide what would be the best visually. We'll likely want input from Alex and Jared on this, so let's not worry to much about this for now. We could make an issue out of it, if you think it's a big deal

Nope, no need to file an issue.

2021-01-28 23:27 UTC, mozartfish commented on src/lib/aggregation.ts
> +    });
resolved with this commit https://github.com/multinet-app/multimatrix/pull/188/commits/e1bb54b43a69d9a9953df7a107da73ebf0698057

2021-01-28 23:38 UTC, mozartfish commented on src/lib/aggregation.ts
> +    });
resolved with this commit https://github.com/multinet-app/multimatrix/pull/188/commits/304c01d3c9465e7aaf196633c42b9b40eb95063c

2021-01-28 23:40 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +        .remove();
If you look very carefully there is a slightly fast fade for the column labels. I will take these out since I haven't figured out the row exit and I will file an issue since this transition seems like it can be fixed later once I have everything else working

2021-01-28 23:43 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +        .remove();
removed column transition with this commit https://github.com/multinet-app/multimatrix/pull/188/commits/00641546626d6f7684249ef57df52a9750c5c155

2021-01-28 23:49 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +        });
The transition is super cool and applied it with this commit https://github.com/multinet-app/multimatrix/pull/188/commits/13b1fe916b2ebc81e533fa2ece63fe6e749d6307

2021-01-29 16:23 UTC, JackWilb requested changes
Just one minor thing I noticed

2021-01-29 16:23 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +            return `translate(0, 0)`;
This needs to be rotated
```suggestion
            return `translate(0, 0)rotate(-90)`;
```

2021-01-29 16:28 UTC, JackWilb approved these changes

2021-01-29 16:41 UTC, merged