Indent Child Node Rows Close Issue #184
multinet-app/multimatrix pull request #192
Opened 2021-02-01 18:03 UTC by mozartfish

Indent Child Row Labels and close #184

2021-02-02 20:21 UTC, JackWilb requested changes

2021-02-02 20:21 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +
Instead of using a new block here, can we add this style setting near line 465? I would imagine you can just do the `.style()` instead of having to do the whole selection again

2021-02-02 20:21 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
>          .attr('width', labelContainerWidth)
You can solve #193 by modifying this width here

2021-02-02 20:21 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +      });
Same as above. Do we need another code block for this?

2021-02-02 20:39 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
>          .attr('width', labelContainerWidth)
Close #193 https://github.com/multinet-app/multimatrix/pull/192/commits/1485821a03126e30d871d36d2c087152fac0265d

2021-02-05 00:23 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +      });
we need this to be separate because first selection deals specifically with the foreign object which has the paragraph element added to it

2021-02-05 17:36 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +      });
This style is being applied to the p tag in the foreign object though, right? If so, this code should live with that

2021-02-05 17:38 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +      });
Do you mean add the styling to the CSS definition?

2021-02-05 18:05 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +      });
I mean above, where you have

```
        .append('xhtml:p')
        .text((d: Node) => d._key)
        .classed('colLabels', true)
```

replace it with

```
        .append('xhtml:p')
        .text((d: Node) => d._key)
        .style('color', (d: Node) => {
          if (d.type === 'node') {
            return '#aaa';
          } else {
            return 'black';
          }
        })
        .classed('colLabels', true)
```

2021-02-05 18:06 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +      });
Instead of making a new selection

2021-02-05 20:08 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +      });
this change produces this 
![image](https://user-images.githubusercontent.com/24800816/107083665-d7597f00-67aa-11eb-81ad-d594b34429a0.png)

2021-02-05 20:08 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +      });
the child labels are black in this picture instead of grey

2021-02-05 20:42 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +      });
That image is from the wrong branch. We don't have node coloring here

2021-02-05 20:43 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +      });
I pushed the change to fix it. If it's working on your end, will you resolve these 2 open threads

2021-02-05 20:43 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
>          .attr('width', labelContainerWidth)
Moved your close statement to the PR description

2021-02-05 20:44 UTC, JackWilb approved these changes

2021-02-05 21:46 UTC, merged