Hierarchy (Cell Colors and Legends)
multinet-app/multimatrix pull request #194
Opened 2021-02-02 23:42 UTC by mozartfish

Close #186
Close #187 
Close #189

2021-02-03 20:17 UTC, gotdairyya commented on src/components/Controls.vue
> +        .labelFormat(format('.0f'));
you could make this one line by removing 91-98

and adding the logic to 102
`.cells(colorScale.domain()[1] >= 5 ? 5 : 0)`

2021-02-03 20:19 UTC, gotdairyya commented on src/components/Controls.vue
> +        .labelFormat(format('.0f'));
same comment for the code below

2021-02-03 20:22 UTC, gotdairyya commented on src/components/MultiMatrix/MultiMatrix.vue
> +              }
I don't understand why this code block is the same as 659-668

2021-02-03 21:16 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +              }
This was a duplicate section of code because there were some edge cases I couldn't figure out how to handle with the number of visualized children nodes.

2021-02-03 21:17 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +              }
The duplicate code snippet allows for displaying the children nodes if there are any children being visualized for the aggregated matrix

2021-02-05 00:20 UTC, mozartfish commented on src/components/Controls.vue
> +        .labelFormat(format('.0f'));
fixed with this commit https://github.com/multinet-app/multimatrix/pull/194/commits/e488f0bc109223ef0e6ace7b8b33792af4471276

2021-02-05 18:04 UTC, JackWilb requested changes
Thanks for this work, Pranav. I have a couple simplifications for you that will make the code a little more elegant. In general, I agree with Derya, we should try to reduce the number of duplicated code chunks so it's easier to refactor at a later date.

There's still an issue with the connection count on a directional network. The children add up to 2 * the aggr row count. I would guess the problem lies in aggregation.ts, but you'll have to do some more debugging to see.

2021-02-05 18:04 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +              }
Let's always have a high opacity and toggle the legends it with a v-if in controls.vue instead. You can probably remove this when you make the v-if change

2021-02-05 18:04 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +              }
Same as on the other similar code block

2021-02-05 18:04 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +          }
Another spot to simplify with an OR
```suggestion
          if (d.rowCellType === 'childnode' || d.colCellType === 'childnode') {
            return this.childColorScale(d.z);
          }
```

2021-02-05 18:04 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +          }
Another OR
```suggestion
          if (d.rowCellType === 'childnode' || d.colCellType === 'childnode') {
            return this.childColorScale(d.z);
          }
```

2021-02-05 18:04 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +            aggrLegend.selectAll('g').style('opacity', 0.9);
Remove this in favor of the v-if

2021-02-05 18:18 UTC, JackWilb commented
I also just noticed that clicking on the cell of a supernode will collapse and expand the rows. That should just be on the row labels

2021-02-05 18:21 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +            cell.colCellType === 'undefined'
fixed with this commit https://github.com/multinet-app/multimatrix/pull/194/commits/7e2084ed0a045d02fa586813b296af6b12702a5a

2021-02-05 20:01 UTC, mozartfish commented on src/components/Controls.vue
> +          @updateChildMatrixLegendScale="createChildMatrixLegend"
fixed with this commit https://github.com/multinet-app/multimatrix/pull/194/commits/087f3fb82d5d861110f82e9ea00beace35905073

2021-02-05 20:01 UTC, mozartfish commented on src/components/Controls.vue
> +        .cells(colorScale.domain()[1] >= 5 ? 5 : 0)
fixed with this commit https://github.com/multinet-app/multimatrix/pull/194/commits/087f3fb82d5d861110f82e9ea00beace35905073

2021-02-08 19:57 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +            aggrLegend.selectAll('g').style('opacity', 0.9);
fixed with these commits 
https://github.com/multinet-app/multimatrix/pull/194/commits/0d0ac978195c15588f5e01ed13b5927c6c24f166
https://github.com/multinet-app/multimatrix/pull/194/commits/a9a6c0cb3bdd1499453d5b02eb028e913f2da872

2021-02-08 19:58 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +              }
fixed with these commits 
https://github.com/multinet-app/multimatrix/pull/194/commits/0d0ac978195c15588f5e01ed13b5927c6c24f166
https://github.com/multinet-app/multimatrix/pull/194/commits/a9a6c0cb3bdd1499453d5b02eb028e913f2da872

2021-02-08 20:12 UTC, mozartfish commented on src/components/Controls.vue
> +        </div>
fixed with these commits 
https://github.com/multinet-app/multimatrix/pull/194/commits/0d0ac978195c15588f5e01ed13b5927c6c24f166
https://github.com/multinet-app/multimatrix/pull/194/commits/a9a6c0cb3bdd1499453d5b02eb028e913f2da872

2021-02-08 20:12 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +              }
fixed with these commits 
https://github.com/multinet-app/multimatrix/pull/194/commits/0d0ac978195c15588f5e01ed13b5927c6c24f166
https://github.com/multinet-app/multimatrix/pull/194/commits/a9a6c0cb3bdd1499453d5b02eb028e913f2da872

2021-02-08 22:39 UTC, JackWilb requested changes
Looks almost ready to go. I just wonder if we could clean up some of the logic by just having one bool to trigger the changes to the legend. Let me know if that's possible

2021-02-08 22:39 UTC, JackWilb commented on src/components/Controls.vue
> +      showChildLegend: false,
Could this be tracked with one boolean? I would imagine that `showNonAggrLegend = !showAggrLegend` and `showNonAggrLegend = !showChildLegend`

2021-02-08 22:39 UTC, JackWilb commented on src/components/Controls.vue
> +        .cells(colorScale.domain()[1] >= 5 ? 5 : 0)
Is this why we have 5 cells even when there is only 0 or 1 connection?

2021-02-08 22:39 UTC, JackWilb commented on src/components/Controls.vue
> +        .cells(colorScale.domain()[1] >= 5 ? 5 : 0)
This should be addressed in a follow up issue

2021-02-08 22:39 UTC, JackWilb commented on src/components/Controls.vue
> +    },
Again, do we need 3 functions here if we can handle it with just one boolean?

2021-02-08 22:51 UTC, mozartfish commented on src/components/Controls.vue
> +        .cells(colorScale.domain()[1] >= 5 ? 5 : 0)
fixed with this commit https://github.com/multinet-app/multimatrix/pull/194/commits/177620f96bfa7493a97cb38ef7296ef067c50cf8

2021-02-08 23:06 UTC, JackWilb commented on src/components/Controls.vue
> +        .cells(colorScale.domain()[1] >= 5 ? 5 : 0)
Nice fix!

2021-02-08 23:08 UTC, JackWilb commented on src/components/Controls.vue
> +      showChildLegend: false,
After reviewing your video, we should use 2 booleans. We should use `showAggrLegend` and `showChildLegend`. It doesn't make sense to have `showAggrLegend` and `showNonAggrLegend` since `showAggrLegend` is equal to `!showAggrLegend`

2021-02-08 23:22 UTC, mozartfish commented on src/components/Controls.vue
> +    },
fixed with this commit https://github.com/multinet-app/multimatrix/pull/194/commits/0c6d4405896d1f970d63e93db896ac039f77dd36

2021-02-08 23:22 UTC, mozartfish commented on src/components/Controls.vue
> +      showChildLegend: false,
fixed with this commit https://github.com/multinet-app/multimatrix/pull/194/commits/0c6d4405896d1f970d63e93db896ac039f77dd36

2021-02-09 00:22 UTC, JackWilb requested changes
I spotted a couple of remnant and had a suggestion for a slight refactor. Let's clean these up and get it merged -- I don't want to delay you with another round of review :smile:

2021-02-09 00:22 UTC, JackWilb commented on src/components/Controls.vue
>          .attr('transform', 'translate(10, 60)');
This code looks dangerous. What if you have a legend with 5 cells and then it switches to a legend of 2 cells? We should remove the original legend before we remake the new one.

We should solve this in a follow up so we don't delay this PR. Please make an issue

2021-02-09 00:22 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +    },
Remnant to be removed

2021-02-09 00:22 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +        showNonAggrLegend,
Remove this, too

2021-02-09 00:22 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +        showNonAggrLegend,
Remove this, too

2021-02-09 00:22 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +    },
Since you're emitting 'aggregate' and 'child', can we refactor the code in controls.vue to just use one function instead of 2 separate ones to update the child/aggr legend?

2021-02-09 03:04 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +        showNonAggrLegend,
fixed with this commit https://github.com/multinet-app/multimatrix/pull/194/commits/4dde964f22101a9912b7808b650ec8619a36c9d0

2021-02-09 03:04 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +        showNonAggrLegend,
fixed with this commit https://github.com/multinet-app/multimatrix/pull/194/commits/4dde964f22101a9912b7808b650ec8619a36c9d0

2021-02-09 03:04 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +    },
fixed with this commit https://github.com/multinet-app/multimatrix/pull/194/commits/4dde964f22101a9912b7808b650ec8619a36c9d0

2021-02-09 18:07 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +    },
fixed with this commit https://github.com/multinet-app/multimatrix/pull/194/commits/7e7eed06f63e12af3c01c2d87cf26f46b1b25dad

2021-02-09 18:26 UTC, mozartfish commented on src/components/Controls.vue
>          .attr('transform', 'translate(10, 60)');
I don't think this will be an issue because the cells are adjusted according to the scales which are changed in the multimatrix.vue file. I doubled checked the documentation here https://d3-legend.susielu.com/ about this. If need be I can also file an issue about this since I don't have anything to test for this

2021-02-09 18:35 UTC, JackWilb commented on src/components/Controls.vue
>          .attr('transform', 'translate(10, 60)');
#198

2021-02-09 18:35 UTC, JackWilb approved these changes

2021-02-09 19:07 UTC, gotdairyya approved these changes

2021-02-09 19:21 UTC, merged