Fix Aggregation For Visualizing Large Data
multinet-app/multimatrix pull request #208
Opened 2021-02-17 19:30 UTC by mozartfish

This PR fixes bugs that appear in the les mis data that are not visible in the small flight dataset.

Fixed Node Ordering for Aggregating by Group for Les Mis
Close #210 
Close #201 
Close #128 
Close #80 

Opened the following issues for this PR
Open #213 
Open #212 
Open #211 

![image](https://user-images.githubusercontent.com/24800816/108257321-75d2d200-7113-11eb-85b7-baec8d7d43c5.png)

Demonstration of Changes
https://user-images.githubusercontent.com/24800816/109598833-f360ef80-7ace-11eb-92f0-66697f649ecc.mp4

2021-02-17 20:15 UTC, gotdairyya commented
Can you have this branch target to your dev branch rather than master?

2021-03-02 22:51 UTC, JackWilb reviewed
Would you please make a note of which issues you opened because of these changes?

2021-03-02 23:02 UTC, JackWilb requested changes
Generally it looks good. Just a few instance of the same issue that should be really easy to clean up

2021-03-02 23:02 UTC, JackWilb commented on src/lib/aggregation.ts
> +        if (parentNodeID) {
Same as above

2021-03-02 23:02 UTC, JackWilb commented on src/lib/aggregation.ts
> +  if (expandNodes && expandLinks) {
Same as above

2021-03-02 23:02 UTC, JackWilb commented on src/lib/aggregation.ts
> +      if (childNode) {
A couple more to fix

2021-03-02 23:02 UTC, JackWilb commented on src/lib/aggregation.ts
> +  if (retractNodes && retractLinks) {
The last 2 😄

2021-03-03 00:55 UTC, mozartfish commented on src/lib/aggregation.ts
> +  if (retractNodes && retractLinks) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/208/commits/6dfbea5a134cba6d71d69051872c0e1d559f7788

2021-03-03 00:55 UTC, mozartfish commented on src/lib/aggregation.ts
> +      if (childNode) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/208/commits/6dfbea5a134cba6d71d69051872c0e1d559f7788

2021-03-03 00:56 UTC, mozartfish commented on src/lib/aggregation.ts
> +  if (expandNodes && expandLinks) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/208/commits/6dfbea5a134cba6d71d69051872c0e1d559f7788

2021-03-03 00:56 UTC, mozartfish commented on src/lib/aggregation.ts
> +        if (parentNodeID) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/208/commits/6dfbea5a134cba6d71d69051872c0e1d559f7788

2021-03-03 00:56 UTC, mozartfish commented on src/lib/aggregation.ts
> +      if (childNode) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/208/commits/6dfbea5a134cba6d71d69051872c0e1d559f7788

2021-03-03 00:56 UTC, mozartfish commented on src/lib/aggregation.ts
> +  if (superNode) {
resolved with this commit https://github.com/multinet-app/multimatrix/pull/208/commits/6dfbea5a134cba6d71d69051872c0e1d559f7788

2021-03-03 17:22 UTC, JackWilb requested changes

2021-03-03 17:22 UTC, JackWilb commented on src/lib/aggregation.ts
> +      if (childNode) {
This doesn't look to be fixed

2021-03-03 17:22 UTC, JackWilb commented on src/lib/aggregation.ts
> +  if (retractNodes && retractLinks) {
This doesn't look to be fixed

2021-03-03 17:30 UTC, JackWilb approved these changes

2021-03-03 17:32 UTC, merged