Aggregation UI Buttons
multinet-app/multimatrix pull request #219
Opened 2021-03-16 05:03 UTC by mozartfish

This PR adds icons for the expand/retract matrix view when the network is aggregated on a single attribute. 
The following issues were addressed:
Close Issue #213 
Close Issue #211 
Close Issue #210 
Close Issue #201 

Issues associated with this PR:
https://github.com/multinet-app/multimatrix/issues/218 
https://github.com/multinet-app/multimatrix/issues/212

Demonstration of this PR (

https://user-images.githubusercontent.com/24800816/111258443-3a280c80-85da-11eb-8573-98815b5aac8b.mp4

2021-03-16 19:18 UTC, JackWilb commented
This doesn't close #213.The matrix is not restored to it's state before aggregation. There are changes to the style, indentation, font color, etc. that need to be removed.

It doesn't seem to have any code that would affect #210.

I'm going to check on #201 and #211 manually when I get to a more thorough review.

Another note here. I think we should solve #218 here since it's key to this functionality. I can help you with that/see if I can get it working to take it off your plate, if you'd like.

2021-03-17 02:17 UTC, JackWilb commented
Added 0d2b063 to fix the issue that was causing #218

2021-03-17 02:24 UTC, JackWilb commented
#211 is fixed. I need to take a deeper look at #201, but I'll do that tomorrow when I give you a full review here, since it will take me a while to pull up some test cases. Looks good so far from what I can see! I'm excited to get this merged

2021-03-17 22:24 UTC, JackWilb requested changes
Looking good! I just found a few things you can clean up and I had some general questions about why some things changed.

My final approval will still be waiting on me checking #201 after these fixes

2021-03-17 22:24 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +
If you just toggle enableGraffinity on and off without doing an aggregation, this breaks.

2021-03-17 22:24 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +              if (this.clickMap.get(nodeID) === true) {
```suggestion
              if (this.clickMap.get(d.id) === true) {
```

2021-03-17 22:24 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +              if (this.clickMap.get(nodeID) === true) {
```suggestion
              if (this.clickMap.get(d.id) === true) {
```

2021-03-17 22:24 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +          .attr('transform', 'scale(0.6)translate(-127, 2)');
If you do the translate before the scale here, you can use the same number as below in line 753. Then refactor that into a variable so we don't have to keep track of all of these magic numbers

2021-03-17 22:24 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +          if (this.enableGraffinity === true) {
```suggestion
          if (this.enableGraffinity) {
```

2021-03-17 22:24 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +      }
Why move this here? I prefer it where it was

2021-03-17 22:24 UTC, JackWilb commented on src/lib/aggregation.ts
> +    newNode.type = undefined;
Why do you need to do this? Should the `nonAggrNodes` always have `type = undefined`?

2021-03-18 15:26 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +      }
This was moved here because it was originally outside outside of the graffinity code. Once I add the (enableGraffinity) check this was moved inside with the row icon expand/retract code. I added this outside to reflect the change but it seems to make more sense where it was originally

2021-03-18 16:06 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +      }
I added the green highlight both inside and outside so it looks something like this 
![image](https://user-images.githubusercontent.com/24800816/111658074-445c2d80-87c9-11eb-8b0c-c406afb3c892.png)

2021-03-18 16:57 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +      }
solution with this commit https://github.com/multinet-app/multimatrix/pull/219/commits/1bae6c3becff4b0881fa3ba2cce4d4a390071c8a

2021-03-18 16:59 UTC, mozartfish commented on src/lib/aggregation.ts
> +    newNode.type = undefined;
In the supergraph function the non-aggregated network is preprocessed and after the preprocessing all the nodes and links have types associated with them. The types inform the correct cell color so I had to change the type to undefined. I've removed going back to the original state for now to make this PR easier to remove. I think a better solution would be creating a button and triggering an event to rebuild the matrix

2021-03-18 18:41 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +          if (this.enableGraffinity === true) {
fixed with this commit https://github.com/multinet-app/multimatrix/pull/219/commits/6a00465fd4f000d7e37fd1a09ebea26a29eba1d3

2021-03-18 18:41 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +              if (this.clickMap.get(nodeID) === true) {
fixed with this commit https://github.com/multinet-app/multimatrix/pull/219/commits/53ec2351fbe6fb91c755923a233435c6b103d6e6

2021-03-18 18:42 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +              if (this.clickMap.get(nodeID) === true) {
fixed with this commit https://github.com/multinet-app/multimatrix/pull/219/commits/53ec2351fbe6fb91c755923a233435c6b103d6e6

2021-03-18 18:42 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +
Removed this code for a different PR

2021-03-18 18:42 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +
fixed with this commit https://github.com/multinet-app/multimatrix/pull/219/commits/4412df9c6e3013704886376036f324576d6cad39

2021-03-18 18:46 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +          .attr('transform', 'scale(0.6)translate(-127, 2)');
Line 753 is contains the emit function code. Is there another line that you were referring to?

2021-03-19 21:30 UTC, JackWilb requested changes
Almost good to go. Just a couple remaining things

2021-03-19 21:30 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +          .attr('transform', 'scale(0.6)translate(-127, 2)');
It's now 734

2021-03-19 21:30 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +          })
This is now captured on 787
```suggestion
        rowEnter
```

2021-03-19 21:30 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +              .attr('cursor', 'pointer');
This will cause strange behavior i think, it should be reverted to what it was before. Check what it changed from to fix this.

2021-03-21 22:02 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +          .attr('transform', 'scale(0.6)translate(-127, 2)');
Fixed with this commit https://github.com/multinet-app/multimatrix/pull/219/commits/133d33975da09a1542edda012bef597aa9aec121

2021-03-22 03:23 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +              .attr('cursor', 'pointer');
Fixed with this commit https://github.com/multinet-app/multimatrix/pull/219/commits/3cff4255757d278f114ab2bfa0afd10f54b572f5

2021-03-22 03:24 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +      }
The previous commit was buggy. Found a new solution which I applied to both the row and column labels
https://github.com/multinet-app/multimatrix/pull/219/commits/3cff4255757d278f114ab2bfa0afd10f54b572f5

2021-03-22 16:39 UTC, JackWilb approved these changes

2021-03-22 16:41 UTC, merged