Restore Matrix
multinet-app/multimatrix pull request #222
Opened 2021-03-22 14:27 UTC by mozartfish

This PR implements restoring the matrix to its original non-aggregated state when the user toggles the enable graffinity features to the left. This PR builds upon the following PR and its associated issues: Aggregation UI Buttons

Close #164

2021-03-23 20:55 UTC, JackWilb requested changes
Looks good, code-wise. There is a bug though. If you enable graffinity features and then disable them without aggregating, it deletes the network

2021-03-23 21:48 UTC, mozartfish commented
Fix the disable aggregation error https://github.com/multinet-app/multimatrix/pull/222/commits/586e5aefc6c6440c68e6d1307b85fefcbae81c72

2021-03-23 22:19 UTC, JackWilb requested changes
Let's call this variable `aggregated`. You need to initialize it as false, set it to true when the network aggregation is called, and then set it back to false once the matrix has been reset to its initial state. 

Another quick note, you don't need to do `this.enableGraffinity === false`, just do `!this.graffinity`

2021-03-24 04:59 UTC, mozartfish commented
Fix variable names to aggregated and clean up code with this commit https://github.com/multinet-app/multimatrix/pull/222/commits/5c0bceff082aeb153db3a5d0878e7755a941e434

2021-04-06 22:17 UTC, JackWilb requested changes
Looks good overall. The code is in the wrong place, though. It should be in the rendering method. I'm happy to fix that if you can't figure it out

2021-04-06 22:17 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +        this.clickMap.clear();
```suggestion
      if (!this.enableGraffinity && this.aggregated === true) {
        // Clear the click map so correct icons are drawn for aggregation
        this.clickMap.clear();
```

2021-04-06 22:17 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +          .classed('rowLabels', true);
This is in the wrong spot. It should be a part of the render method. I can move this if you'd prefer that

2021-04-06 22:29 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +          .classed('rowLabels', true);
If you can move this section that would be really helpful. Thank you!

2021-04-08 18:41 UTC, JackWilb approved these changes
Actually, I'm fine with where this is. Combining it into the render function will be significant work and this is good for now

2021-04-08 19:16 UTC, merged