Add labels for keeping track of the number of children that belong to a supernode
multinet-app/multimatrix pull request #226
Opened 2021-03-25 02:05 UTC by mozartfish

2021-03-25 02:31 UTC, JackWilb commented
Instead of making another variable on the nodes, couldn't you just use `CHILDREN.length`?

2021-04-06 22:20 UTC, JackWilb commented
This looks great. It's probably missing a header and shouldn't be console logging

2021-04-12 18:54 UTC, mozartfish commented
> This looks great. It's probably missing a header and shouldn't be console logging

removed print statements with this commit https://github.com/multinet-app/multimatrix/pull/226/commits/54f046197792e7a81a7c35710a295764a645a0b1

added child aggregation count with this commit https://github.com/multinet-app/multimatrix/pull/226/commits/e55951fef997f6d0664ba5f30b9aa985079a599e

2021-04-12 21:17 UTC, JackWilb requested changes

2021-04-12 21:17 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +
This should only happen if the matrix is aggregated and be removed when we're not aggregating

2021-04-12 21:17 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +        .classed('countLabels', true);
Same here, only if the matrix is aggregated

2021-04-12 21:17 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +      return uniqueValues.length > uniqueValues.length + 1;
This is always false. It's basically:

```
return x > x+1
```
and x has is a non-negative integer. We should just switch this to 15 instead of 5.

2021-04-14 19:43 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +      return uniqueValues.length > uniqueValues.length + 1;
fixed with this commit https://github.com/multinet-app/multimatrix/pull/226/commits/3c8c4e7cb7ca3f006cf32b073269d0ec43e70f3d

2021-04-14 19:43 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +        .classed('countLabels', true);
fixed with this commit https://github.com/multinet-app/multimatrix/pull/226/commits/54463bfbab3f5e9135bfc70e485788a8910201a1

2021-04-14 19:43 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +
fixed with this commit https://github.com/multinet-app/multimatrix/pull/226/commits/54463bfbab3f5e9135bfc70e485788a8910201a1

2021-04-14 19:44 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +        .classed('countLabels', true);
fixed with this commit https://github.com/multinet-app/multimatrix/pull/226/commits/5542450b35e496554c1812ef183a38b4ac6c9441

2021-04-14 19:44 UTC, mozartfish commented on src/components/MultiMatrix/MultiMatrix.vue
> +
fixed with this commit https://github.com/multinet-app/multimatrix/pull/226/commits/5542450b35e496554c1812ef183a38b4ac6c9441

2021-04-14 21:27 UTC, JackWilb commented on src/components/MultiMatrix/MultiMatrix.vue
> +      return uniqueValues.length > uniqueValues.length + 1;
Added my desired fix in 63acc7e

2021-04-14 22:03 UTC, JackWilb approved these changes

2021-04-14 22:04 UTC, merged