Subset large networks
multinet-app/multimatrix pull request #246
Opened 2021-05-06 22:29 UTC by gotdairyya

Closes #207 

This branch creates a dialog for users to subset large networks. There are two options for subsetting:
1. Choosing a max number of edges to visualize
2. Choosing a node attribute to aggregate by

**To Do:**

- [ ] Add subset option to aggregate by categorical attribute
- [ ] Make it look nicer
- [ ] Discuss and determine whether current AQL query is appropriate for subsetting

2021-05-06 23:45 UTC, JackWilb requested changes
Looks great so far, even though I've left a ton of comments. Some of them are just for general style and simplification and I've left a larger change where you asked for my help with refactoring. Ask questions where things aren't clear 😄

2021-05-06 23:45 UTC, JackWilb commented on src/components/Alert.vue
> +    />
```suggestion
    <filter-overlay
      v-if="loadError.message === 'The network you are loading is too large'"
    />
```

2021-05-06 23:45 UTC, JackWilb commented on src/store/index.ts
> +    },
I've just learned that we don't need to make these getters that return the value like this (I have them removed in the lineup branch). Instead we should delete it and use `store.state.nodeTableName` when we're using the value elsewhere

```suggestion
```

2021-05-06 23:45 UTC, JackWilb commented on src/store/index.ts
> +      // Check node and table size
It's a bit cleaner if we add a line of white space above this block
```suggestion
     
      // Check node and table size
```

2021-05-06 23:45 UTC, JackWilb commented on src/store/index.ts
> +      const resolvedSizePromises = await Promise.all(sizePromises);
```suggestion
      const sizePromises = networkTables.nodeTables.map((table) => api.aql(workspaceName, `FOR doc IN ${table} COLLECT WITH COUNT INTO length RETURN length`));
      const resolvedSizePromises = await Promise.all(sizePromises);
```

2021-05-06 23:45 UTC, JackWilb commented on src/store/index.ts
> +      }
```suggestion
      }

```

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +            <v-list>
Is there a specific reason you chose a list here, or it was just in the examples you found?

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +    <v-app id="filterOverlayDialog">
We only really need IDs to reference them elsewhere
```suggestion
  <div>
    <v-app>
```

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +    <v-app id="filterOverlayDialog">
I'd recommend not using v-app here. It could cause some weird css issues. Let's just remove it, since the div is a good containing element

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +    max: 300,
You don't need to make these data props if you're just using them once in the template. Just put the number right in the template, e.g. `:max="300"`. Same for overlay, max, and min.

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +                  :ticks="true"
```suggestion
                  ticks
```

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +    zIndex: 0,
This appears to be unused
```suggestion
```

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +                >
This will make the label visible
```suggestion
                  thumb-label
                  thumb-color="primary"
                >
```

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +              color="teal"
Take this or leave this. I think Jared has a better idea of what to do, but this will make the button blue
```suggestion
              color="primary"
```

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +            >
`tile` removes the radius from the button. It's still slightly too large though on my machine with this change
```suggestion
              @click="filterNetwork"
              tile
            >
```

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +
```suggestion

```

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +import Vuex from 'vuex';
```suggestion
```

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +      this.overlay = false;
Maybe do this after the function succeeds? What if it fails here?

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +/* eslint-disable no-restricted-syntax */
I have suggestions for how to fix this below
```suggestion
```

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +      });
You'd asked for my help refactoring this. Here's what I came up with. I used a set to track the `_id`, instead of key since that relies on the table. If you had nodes from 2 different tables with the same key, you might have had problems, and a set makes the logic much cleaner.
```suggestion
      newTablePromise.then((promise) => {
        const aqlNetwork: Network = { nodes: [], edges: [] };

        // check for duplicates
        const nodeChecker: Set<string> = new Set();
        promise.forEach((path) => {
          path.vertices.forEach((node: Node) => {
            nodeChecker.add(node._id);
          });
        });

        // create network in json format
        promise.forEach((path) => {
          path.vertices.forEach((node: Node) => {
            if (nodeChecker.has(node._id)) {
              aqlNetwork.nodes.push(node);
              nodeChecker.delete(node._id);
            }
          });
          aqlNetwork.edges = path.edges;
        });

        // Update state with new network
        store.commit.setNetwork(aqlNetwork);
      });
```

2021-05-06 23:45 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +      const aqlQuery = `FOR nodes in ${this.nodeTable} LIMIT ${this.subsetAmount} FOR v,e,p in 1..4 ANY nodes GRAPH '${this.workspace}' LIMIT ${this.subsetAmount} RETURN p`;
I think `GRAPH '${this.workspace}'` is a bug

2021-05-06 23:49 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +      });
If you accept this change, you'll also need to mess with the imports to add `Node`

2021-05-07 00:18 UTC, gotdairyya commented on src/components/Alert.vue
> +  },
Ok good to know, thank you!

2021-05-07 00:20 UTC, gotdairyya commented on src/components/Alert.vue
> +    // Add button
Oh yes that makes total sense

2021-05-07 00:23 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +            <v-list>
Yes, there is going to be one more option for how to subset (hence the list, but maybe it's not necessary?)

2021-05-07 00:24 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +              color="teal"
No, I think this is the right thing to do (plus we can ask Jared)

2021-05-07 00:26 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +      this.overlay = false;
What do you mean by "this" in the first part of your comment?
And yes, I will add what happens if it fails

2021-05-07 00:26 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +      const aqlQuery = `FOR nodes in ${this.nodeTable} LIMIT ${this.subsetAmount} FOR v,e,p in 1..4 ANY nodes GRAPH '${this.workspace}' LIMIT ${this.subsetAmount} RETURN p`;
what do you mean?

2021-05-07 00:28 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +      });
A set is so clever! and yes this refactoring is much easier to follow -- thank you!

2021-05-07 00:29 UTC, gotdairyya commented on src/store/index.ts
> +    },
oh, so we're completely removing all the getters and then we can still use `store.state.nodeTableName` ?

2021-05-07 00:30 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +      this.overlay = false;
I was thinking the overlay shouldn't hide until it's done processing

2021-05-07 00:31 UTC, JackWilb commented on src/store/index.ts
> +    },
Yeah, the getters should only be used if you need to do something like adding 2 different values from the store (and only if it's used across multiple components)

2021-05-07 00:37 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +    max: 300,
Don't I need to keep `overlay` as a data prop though because it needs to be updated on click

2021-05-07 00:49 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +      this.overlay = false;
Oh oh, you are so right.

2021-05-07 00:51 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +/* eslint-disable no-restricted-syntax */
Resolved with c7ca8ee84382529a376ec2ea73171a6c4c7c39f3

2021-05-07 00:52 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +      });
Resolved but slightly modified. Since there can be multiple edges in a path I add a map. Closed with c7ca8ee84382529a376ec2ea73171a6c4c7c39f3

2021-05-07 01:08 UTC, gotdairyya commented
> You should consider opening an issue to convert this code to composition API style (I'm trying to write all our new components in that style), and you should think about catching errors with the AQL and how that will work.

New issue opened #247 for composition API. I may need help with it since some of it still doesn't make sense.

2021-05-07 15:13 UTC, JackWilb requested changes
Another couple of suggestions, but this is looking almost ready to go

2021-05-07 15:13 UTC, JackWilb commented on src/components/Alert.vue
> +import Vue from 'vue';
Is this unused now?

2021-05-07 15:13 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +            <v-list>
I don't think this matters, for now. So long as it works :)

2021-05-07 15:13 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +            >
Looks like this wasn't fixed

2021-05-07 15:13 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +          path.edges.map((edge: Link) => aqlNetwork.edges.push(edge));
This shouldn't be any different from 
```suggestion
          aqlNetwork.edges = path.edges;
```
All you're doing is pushing the edge for each edge. Instead of looping and pushing, we can just assign

2021-05-07 15:16 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +    max: 300,
Instead of having the `overlay`, you could just update the `loadError` and it would unmount the component

2021-05-07 16:00 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +          path.edges.map((edge: Link) => aqlNetwork.edges.push(edge));
No, it is different, because every time you loop through the path it replaces the edges in aqlNetwork, so you only end up with the last set of paths

2021-05-07 16:04 UTC, gotdairyya commented on src/components/Alert.vue
> +import Vue from 'vue';
yes, closed with 3d4febd0ec788f85fca2a70b17c7ef0c4ed89fbf

2021-05-07 16:41 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +          path.edges.map((edge: Link) => aqlNetwork.edges.push(edge));
Updated with spread

2021-05-08 05:03 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +            <v-list>
fixed with updating the state: a1075fc2cbe0cad2c604b134dc95d0a19eb74846

2021-05-08 05:04 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +    <v-app id="filterOverlayDialog">
Removed with 306ec78fe825ed4c453b89b8a05b982b7a755bf7

2021-05-08 05:04 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +    max: 300,
Closed with a1075fc2cbe0cad2c604b134dc95d0a19eb74846

2021-05-08 05:05 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +      this.overlay = false;
Resolved with a1075fc2cbe0cad2c604b134dc95d0a19eb74846

2021-05-08 05:05 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +      const aqlQuery = `FOR nodes in ${this.nodeTable} LIMIT ${this.subsetAmount} FOR v,e,p in 1..4 ANY nodes GRAPH '${this.workspace}' LIMIT ${this.subsetAmount} RETURN p`;
Resolved with a1075fc2cbe0cad2c604b134dc95d0a19eb74846
Turns out the i should've been call the network name after `GRAPH`

2021-05-10 16:32 UTC, JackWilb requested changes
We're getting there. Just a couple more issues to address with the AQL query and catching the errors it could have

2021-05-10 17:28 UTC, gotdairyya commented on src/store/index.ts
> +    },
Closed with 63b36bc1f7f333e1304537a983526034a165a675

2021-05-10 18:03 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +      const aqlQuery = `FOR nodes in ${this.nodeTable} LIMIT ${this.subsetAmount} FOR v,e,p in 1..4 ANY nodes GRAPH '${store.state.networkName}' LIMIT ${this.subsetAmount} RETURN p`;
Resolved the double (or more) counting with e61f2f2e77586f04f90e953d26edd128c1f80ee8

2021-05-10 20:44 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +      const aqlQuery = `FOR nodes in ${this.nodeTable} LIMIT ${this.subsetAmount} FOR v,e,p in 1..4 ANY nodes GRAPH '${store.state.networkName}' LIMIT ${this.subsetAmount} RETURN p`;
Now outdate with new query from cd1f4153c11c4bbd4b12db06cf99e12256429297

2021-05-10 21:04 UTC, JackWilb requested changes

2021-05-10 21:04 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +        if (store.state.loadError.message === '' && typeof newAQLNetwork === 'undefined') {
`store.state.loadError.message === ''` will always equal false if there is a network error since the error is what causes this component to load. It should be `store.state.loadError.message === 'The network you are loading is too large'`. Basically if the error hasn't changed and the aql is undefined then we'd assume it was the network that isn't working.

2021-05-10 21:04 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +        }
Add an else here as a catch all for any other type of error. It can be similar to the "Something unexpected ocurred" from `fetchNetwork`

2021-05-10 21:04 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +      if (newAQLNetwork !== undefined) {
```suggestion
      }

      if (newAQLNetwork !== undefined) {
```

2021-05-10 21:04 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +          const aqlNetwork: Network = Object.assign(promise)[0];
Do you need the object.assign here?
```suggestion
          const aqlNetwork: Network = promise[0];
```

2021-05-10 22:20 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +        if (store.state.loadError.message === '' && typeof newAQLNetwork === 'undefined') {
Oh great catch! Resolved with 7236c1fd9752998103169d17aeb7e37a58009e05

2021-05-10 22:20 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +        }
Resolved with 7236c1fd9752998103169d17aeb7e37a58009e05

2021-05-10 22:51 UTC, JackWilb requested changes
Just a couple unused imports, some whitespace, and an explicit any to fix. Then it's ready to go!

2021-05-10 22:51 UTC, JackWilb commented on src/components/Alert.vue
> +import Vue from 'vue';
This needs to be removed

2021-05-10 22:51 UTC, JackWilb commented on src/store/index.ts
> +    },
```suggestion

    setNodeTableNames(state, nodeTableNames: string[]) {
      state.nodeTableNames = nodeTableNames;
    },

    setEdgeTableName(state, edgeTableName: string | null) {
      state.edgeTableName = edgeTableName;
    },

```

2021-05-10 22:51 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +import { Network, Node } from '@/types';
Unused import
```suggestion
import { Network } from '@/types';
```

2021-05-10 22:51 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +      let newAQLNetwork: Promise<any[]> | undefined;
```suggestion
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      let newAQLNetwork: Promise<any[]> | undefined;
```

2021-05-10 23:11 UTC, JackWilb approved these changes
Great work! Thanks for being open to all my 79 requests :joy:. This is a great improvement for the app

2021-05-11 04:16 UTC, merged