Connectivity query
multinet-app/multimatrix pull request #274
Opened 2021-06-11 20:35 UTC by gotdairyya

At the moment there is no functionality and the UI is ugly.

I wanted to get some initial feedback from @JackWilb about whether I set the component up correctly (I didn't use composition API).

- [x] Fix logic to show appropriate number of dropdowns (currently doubled)
- [x] Add more query logic (like _contains_ and boolean operators
- [x] Hook up AQL logic

2021-06-18 16:51 UTC, gotdairyya commented
@JackWilb can you help with the following? I have stared at it too long to figure out what is wrong

- [ ] there is something strange happening where not all of the node values in the template are stored
- [ ] the modulo logic for generating the template doesn't work with odd number hops
- [ ] and I'm not sure the AQL query works (it returns more nodes than when I use the Arango platform

2021-06-22 20:34 UTC, JackWilb requested changes
I'd like to review the AQL query, too, but the variable names and what they mean are confusing me a little. Would you mind taking care of those first (using my suggestions or coming up with better names) before I get to the query?

2021-06-22 20:34 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +    function submitQuery() {
This needs to check that all the parameters are set appropriately before firing the query. We should tell the user what needs to be addressed if it fails.

2021-06-22 20:34 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +    const edgeCategories: Ref<string[][]> = ref([]);
These two are just the node and edge variables. I don't think you need to make these a list, with the same options repeated each time. You should just have one computed variable for all node variables, and all edge variables. Then you can reference that everywhere. I'm sure this logic exists somewhere else in this app or in the multilink app

2021-06-22 20:34 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +    const edgeQueryOptions: Ref<string[]> = ref([]);
Appears unused. You can remove from the return at the bottom of the `setup()` function, too
```suggestion
```

2021-06-22 20:34 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +    const edgeCategory: Ref<string[]> = ref([]);
Maybe call these `nodeVariable` and `edgeVariable`?

2021-06-22 20:34 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +    const edgeCategorySelection: Ref<string[]> = ref([]);
These could then be `nodeVariableValue` and `edgeVariableValue`

2021-06-22 20:34 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +    const edgeCategories: Ref<string[][]> = ref([]);
Then maybe call them `nodeVariableItems` and `edgeVariableItems`

2021-06-22 20:34 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +    });
`hopsSelection` is only the [1,2,3,4,5]. Don't you want the `2n + 1` variable from above, `displayedHops`?

2021-06-22 21:49 UTC, gotdairyya commented
> I'd like to review the AQL query, too, but the variable names and what they mean are confusing me a little. Would you mind taking care of those first (using my suggestions or coming up with better names) before I get to the query?

yes totally, naming is hard, will fix!

2021-06-23 04:17 UTC, gotdairyya commented on src/components/ConnectivityQuery.vue
> +    function submitQuery() {
Created issue #277

2021-06-23 04:24 UTC, gotdairyya commented on src/components/ConnectivityQuery.vue
> +    const edgeCategorySelection: Ref<string[]> = ref([]);
Resolved with a75f51fa8e1af5a866c69c81eb26f183ebb0f00c

2021-06-23 04:25 UTC, gotdairyya commented on src/components/ConnectivityQuery.vue
> +    const edgeCategory: Ref<string[]> = ref([]);
Resolved with a75f51fa8e1af5a866c69c81eb26f183ebb0f00c

2021-06-23 04:25 UTC, gotdairyya commented on src/components/ConnectivityQuery.vue
> +    const edgeQueryOptions: Ref<string[]> = ref([]);
Resolved with a75f51fa8e1af5a866c69c81eb26f183ebb0f00c

2021-06-23 04:32 UTC, gotdairyya commented on src/components/ConnectivityQuery.vue
> +    });
Resolved with 7193df3411ea8b02d09f12a00a6c2d119aef0ff5

2021-06-23 04:40 UTC, gotdairyya commented on src/components/ConnectivityQuery.vue
> +    const edgeCategories: Ref<string[][]> = ref([]);
Good catch! Resolved with 803107c6eb9445bed29c8e5044705017e55d11c6

2021-06-24 18:14 UTC, JackWilb submitted a review, later dismissed
Looks great! I just saw one thing that might be worth exploring. We could probably merge without this, so I've approved

2021-06-24 18:14 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +      `;
You wanted to clean this up and remove some of what is returned. We should open an issue to track that

2021-06-24 18:14 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +                  nodesSet.add(path.vertices[i]._key);
You should use id here, I think. That would make this more robust to nodes from different tables, since keys can clash across tables

2021-06-24 18:14 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +                  nodesSet.add(path.vertices[i]._key);
Same as above

2021-06-24 18:28 UTC, gotdairyya commented on src/components/ConnectivityQuery.vue
> +      `;
Yup, this is all part of my query rewrite in issue #278

2021-06-24 18:33 UTC, gotdairyya commented on src/components/ConnectivityQuery.vue
> +                  nodesSet.add(path.vertices[i]._key);
yes ok! resolved with 48dfe4ac4154a640e38a9edcab5004a889e4e60f

2021-06-24 18:33 UTC, gotdairyya commented on src/components/ConnectivityQuery.vue
> +                  nodesSet.add(path.vertices[i]._key);
Resolved with 48dfe4ac4154a640e38a9edcab5004a889e4e60f

2021-06-24 18:39 UTC, JackWilb approved these changes

2021-06-24 18:41 UTC, merged