Make aql query more robust
multinet-app/multimatrix pull request #280
Opened 2021-06-25 19:36 UTC by gotdairyya

Will close issue #278 

**To Do:**
- [ ]  * for nodes
- [ ]  edge filtering
- [ ]  AND/OR functionality on edges/nodes <-- needs to be scoped a little more
- [ ]  remove unnecessary arguments
- [ ]  make query not case sensitive

2021-06-25 20:24 UTC, gotdairyya commented
Moved the AND/OR functionality to issue #282

2021-06-25 20:54 UTC, JackWilb requested changes
I see one small change you can make to simplify things even more with the query

In general, I think we should offer more query operators for both nodes and edges. I can see use cases for >, <, !=, etc. Is that something you're considering?

I verified:
- [x]  * for nodes + edges
- [ ]  edge filtering
- [x]  remove unnecessary arguments
- [x]  make query not case sensitive

I can't run a query that queries the network for `edge.value == 15` with no nodes. I'm not sure if that's a query we should allow, or not, though. (looks like this is covered by #283)

2021-06-25 20:54 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
>          let path = (for p in paths RETURN p.paths)
```suggestion
```

2021-06-25 20:54 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +        RETURN {paths: path}
```suggestion
        RETURN {paths: paths[**].paths}
```

2021-06-25 20:54 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
>        }
Why don't these have query operators?

2021-06-25 21:12 UTC, gotdairyya commented on src/components/ConnectivityQuery.vue
>        }
Because edge selection will always be precise for the marclab... But now I'm not sure if it makes sense in other use cases

2021-06-25 23:28 UTC, gotdairyya commented on src/components/ConnectivityQuery.vue
>        }
> I see one small change you can make to simplify things even more with the query
> 
> In general, I think we should offer more query operators for both nodes and edges. I can see use cases for >, <, !=, etc. Is that something you're considering?
> 
> I verified:
> 
> * [x]   * for nodes + edges
> * [ ]   edge filtering
> * [x]   remove unnecessary arguments
> * [x]   make query not case sensitive
> 
> I can't run a query that queries the network for `edge.value == 15` with no nodes. I'm not sure if that's a query we should allow, or not, though. (looks like this is covered by #283)

Yes so currently the first node needs to be selected in order to run a query successfully.
I've also created an issue to address numerical queries #284 , which I think we agreed on slack will be a later functionality

2021-06-26 00:36 UTC, JackWilb approved these changes

2021-06-26 05:02 UTC, merged