Move network variables to store
multinet-app/multimatrix pull request #286
Opened 2021-06-29 20:19 UTC by gotdairyya

This change will make it possible to switch between queries without refreshing the page.
It will also show all possible options for large networks because it will pull the values from the original network.

2021-06-30 13:59 UTC, gotdairyya commented
This code mostly works, there is something going on within the FilterOverlay component where I am calculating the node and edge variables using AQL only if the network was subsetted.

The issue seems to be that the state is empty. This is the error I see: `Property 'setLargeNetworkAttributeValues' does not exist on type '{}'`

I have a feeling that it's due to async loading, but would like to discuss after you take a look

2021-06-30 17:44 UTC, JackWilb requested changes
I think there are some edge cases that need to be considered, but overall, this works great!

2021-06-30 17:44 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +    getAttributes() {
```suggestion
    },

    getAttributes() {
```

2021-06-30 17:44 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +      `;
From the [arango docs](https://www.arangodb.com/docs/stable/aql/fundamentals-document-data.html):

>Data in collections is stored in documents, with each document potentially having different attributes than other documents. This is true even for documents of the same collection.

Therefore, this might not get us all key value pairs. We might need to reformat this query a little

2021-06-30 17:58 UTC, JackWilb commented
Also, I didn't test this locally. I think we should test an example of 1 node table and 2 or more node tables to make sure that expansion works

2021-06-30 18:34 UTC, gotdairyya commented on src/types.ts
> +  edgeAttributes: {[key: string]: string[]};
If we are setting types for everything on upload (hypothetically) I assume we will see the types from upload options -- or am I misinterpreting that? right now everything I have seen is stored as a string

2021-06-30 18:56 UTC, JackWilb commented on src/store/index.ts
> +    },
```suggestion
    setLargeNetworkAttributeValues(state: State, payload: { nodeAttributes: { [key: string]: string[] }; edgeAttributes: { [key: string]: string[] }}) {
      state.nodeAttributes = payload.nodeAttributes;
      state.edgeAttributes = payload.edgeAttributes;
    },
```

2021-06-30 19:38 UTC, JackWilb commented on src/types.ts
> +  edgeAttributes: {[key: string]: string[]};
I made this fix. I just chose unknown since we don't know which it will be exactly

2021-06-30 19:40 UTC, JackWilb commented on src/store/index.ts
> +    },
See 00e4895

2021-07-01 16:16 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +      `;
I do think it gets all key-value pairs...We should definitely test this though, so I opened issue #287 for this (mostly because I don't trust AQL)

2021-07-01 16:29 UTC, gotdairyya commented on src/store/index.ts
> +    },
Closed with 365f9591157159919a5bdfbc77abc63f2b741143

2021-07-01 16:37 UTC, gotdairyya commented
> Also, I didn't test this locally. I think we should test an example of 1 node table and 2 or more node tables to make sure that expansion works

I tested with the Paul Revere dataset. It is not pulling from the second table. I will figure out why.

Also, I am getting a bug with nodes > 1, and edges > 1 in the dropdown. 

To Do:
- [ ] Get values for all node tables
- [ ] Address issue with dropdown logic

2021-07-01 21:40 UTC, JackWilb approved these changes

2021-07-01 21:41 UTC, merged