Draw intermediary nodes matrix
multinet-app/multimatrix pull request #302
Opened 2021-07-13 14:52 UTC by gotdairyya

This table should show the middle paths of a connectivity query.

To do:

- [ ] add labels for rows
- [ ] add symbols above columns to indicate path position

2021-07-13 19:57 UTC, gotdairyya commented
@JackWilb this is a super simple implementation of the intermediary node view

I've added issues for the next steps:
#303 
#304

2021-07-14 01:48 UTC, JackWilb reviewed
It seems like if you run a 2 hop query and then a 3 hop, it doesn't update properly. Maybe that's a more general problem here, that it's not reactive to new update. We'd need to explore that a bit more

Other than that, I've cleaned up some type issues, etc. I also have a couple of questions  for you

2021-07-14 01:48 UTC, JackWilb commented on src/components/IntermediaryNodes.vue
> +          .attr('transform', `translate(${matrixWidth.value * 0.13}, -${margin.top / 4})`);
This numbers seem kind of random. Is there a good reason why it's `0.13` and `... / 4`? Could we make that more obvious for other people who read this code?

2021-07-14 01:48 UTC, JackWilb commented on src/components/IntermediaryNodes.vue
> +          .attr('transform', (_, i: number) => `translate(${xScale(i)}, 0)rotate(-90)`);
Is this code a remnant from something else? Maybe we can remove it :)

2021-07-14 03:32 UTC, gotdairyya commented on src/components/IntermediaryNodes.vue
> +    const sortOrder = computed(() => store.state.connectivityMatrixPaths.nodes.map((node) => node._key).sort());
No I don't think so. I'm checked that I'm using sortOrder where the order matters, but definitely worth discussing a little

2021-07-14 03:33 UTC, gotdairyya commented on src/components/IntermediaryNodes.vue
> +          .attr('transform', `translate(${matrixWidth.value * 0.13}, -${margin.top / 4})`);
yes. this is what I mentioned earlier about the scrappy bits of the code. will try to clean up with more reasonable variables

2021-07-14 03:35 UTC, gotdairyya commented on src/components/IntermediaryNodes.vue
> +          .attr('transform', (_, i: number) => `translate(${xScale(i)}, 0)rotate(-90)`);
Yes! good catch!!

2021-07-14 03:38 UTC, gotdairyya commented on src/components/MultiMatrix.vue
> +    showInterMediateNodes() {
Resolved with 5a6611b029d830a52dac77fa659b6a3ac85f277f

2021-07-14 03:39 UTC, gotdairyya commented on src/components/IntermediaryNodes.vue
> +    });
Yeah still figuring out when to use watcheffect v. computed
Resolved with 5a6611b029d830a52dac77fa659b6a3ac85f277f

2021-07-14 03:39 UTC, gotdairyya commented on src/components/IntermediaryNodes.vue
> +          .attr('transform', (_, i: number) => `translate(${xScale(i)}, 0)rotate(-90)`);
Resolved with 5a6611b029d830a52dac77fa659b6a3ac85f277f

2021-07-14 14:19 UTC, gotdairyya commented on src/components/IntermediaryNodes.vue
> +          .attr('transform', `translate(${matrixWidth.value * 0.13}, -${margin.top / 4})`);
Resolved with b099d20fdc33025a36e61fd774a7df1471277af1

2021-07-14 15:48 UTC, JackWilb commented on src/components/IntermediaryNodes.vue
> +    const sortOrder = computed(() => store.state.connectivityMatrixPaths.nodes.map((node) => node._key).sort());
I see that the labels are right next to the vis, it's probably not an issue

2021-07-14 15:52 UTC, JackWilb requested changes
There's a bunch of extra space that is added if this div is present. You could also open an issue to address the reactivity of the component since it doesn't seem to update if the path length changes or a query is re-run

With div:
![image](https://user-images.githubusercontent.com/36867477/125652572-9ab62c4c-c02e-4035-969d-934353501d8d.png)

Without div:
![image](https://user-images.githubusercontent.com/36867477/125652395-4749291e-5e11-4540-a0d0-2154430ba704.png)

2021-07-14 15:52 UTC, JackWilb commented on src/components/IntermediaryNodes.vue
> +  </div>
```suggestion
  <svg
    id="intNode"
    :width="matrixWidth"
    :height="matrixHeight"
    :viewbox="`0 0 ${matrixWidth} ${matrixHeight}`"
  />
```

2021-07-14 23:48 UTC, gotdairyya commented on src/components/IntermediaryNodes.vue
> +  </div>
I have the div in there to add the extra padding. Do you think I need to remove it?

2021-07-14 23:50 UTC, gotdairyya commented
Ok so aside from the matrix not updating correctly (pushed to issue #311) I think I have addressed all of the issues
Let me know if I should do anything else before merge?

2021-07-15 04:35 UTC, JackWilb commented on src/components/IntermediaryNodes.vue
> +  </div>
I thought it might have a bit too much, but it's okay. We can ask Jared for some feedback at standup

2021-07-15 04:35 UTC, JackWilb approved these changes

2021-07-15 16:09 UTC, merged