Path table update
multinet-app/multimatrix pull request #337
Opened 2021-09-14 20:05 UTC by gotdairyya

With this update, you should be able to click the matrix (after a 1-hop query) and it will display a path table with the paths.

Closes #334

2021-09-14 20:25 UTC, JackWilb commented on src/components/MultiMatrix.vue
> +        })
This removes your on click logic you added below from the cells when they update again.

2021-09-15 17:46 UTC, gotdairyya commented on src/components/MultiMatrix.vue
> +        })
Oh so I should add the logic in both parts right?

2021-09-15 18:22 UTC, JackWilb commented on src/components/MultiMatrix.vue
> +        })
I believe so. I think not having it both places was causing it to be removed when the network updated for me.

2021-09-22 21:10 UTC, JackWilb requested changes
Just one thing I saw. Everything else looks ready to go!

2021-09-22 21:10 UTC, JackWilb commented on src/components/PathTable.vue
> +      // }
Looks like a remnant we can remove
```suggestion
```

2021-09-23 15:33 UTC, JackWilb approved these changes

2021-09-23 15:44 UTC, merged