Edge slicing
multinet-app/multimatrix pull request #372
Opened 2022-02-10 18:59 UTC by gotdairyya

### Does this PR close any open issues?
No.

### Give a longer description of what this PR addresses and why it's needed
This is incorporating the functionality of MultiDynamic into MultiMatrix. It will be more generalized so that it can also account for categorical edge types.

### Provide pictures/videos of the behavior before and after these changes (optional)
Edge slicing lets you pick numerical and date-formated edge variables and create slices.
![image](https://user-images.githubusercontent.com/8480871/153477503-e2e8eba2-b892-4526-aaba-edf4b2d42ff4.png)

Once the slices are created, you can navigate the network along the slice
![image](https://user-images.githubusercontent.com/8480871/153477632-89850a66-eb49-4520-8aa1-d6e5a26139ed.png)

### Are there any additional TODOs before this PR is ready to go?

TODOs:
- [x] Check why variables don't load for networks that need subsetting
- [x] Add metadata to EdgeSlices.vue (toopltip + visualization)
- [x] Fix type issues
- [x] Clear timeline view for the hop query

2022-02-10 21:09 UTC, JackWilb commented on src/components/EdgeSlicing.vue
> +            mdi-cog
Let's use mdi-chevron-up/mdi-chevron-down here. Similar to how it is for visualization options in the main controls component

2022-02-10 21:47 UTC, JackWilb commented on src/store/index.ts
>    NetworkSpec, UserSpec,
Condense into one line

2022-02-10 22:33 UTC, JackWilb approved these changes
Looks good so far, the UI needs some work, as you said. I think it's good to go, but maybe we should hold off until you have a PR for the UI changes.

Also, is there anything different in the edge slicing, and edge slices component that I haven't review in the multidyno?

2022-02-10 22:35 UTC, JackWilb commented on src/components/EdgeSlicing.vue
> +    const cleanedEdgeVariables = computed(() => {
Can these be moved to the store, we have similar logic for the node variable lists there. It would make sense to put similar code together, and maybe we can even reduce some of the logic needed

2022-02-10 22:38 UTC, JackWilb commented
> @JackWilb can you take a look at the to-do I listed? I think the reason it doesn't work is because of when the edge variable list is created. It might need to be generated `onMounted()`

It seems that the list generation relies on `networkOnLoad`, which wouldn't exist if the network doesn't get fetched because it's too big. You might need a refactor of that code if you want to see the list before you have a network downloaded. Also, it would then have to fetch the network split by time slices

2022-02-10 22:42 UTC, gotdairyya commented on src/components/EdgeSlicing.vue
> +            mdi-cog
done

2022-02-10 22:44 UTC, gotdairyya commented on src/store/index.ts
>    NetworkSpec, UserSpec,
done

2022-02-11 00:46 UTC, gotdairyya commented
> Looks good so far, the UI needs some work, as you said. I think it's good to go, but maybe we should hold off until you have a PR for the UI changes.
> 
> Also, is there anything different in the edge slicing, and edge slices component that I haven't review in the multidyno?

nope! I just refactored some of the code so that it works with the MultiMatrix setup, but nothing new yet

2022-02-14 16:20 UTC, gotdairyya commented
Made some bigger changes:
- slices show the number of edges within each section
- now slices can be made along categorical variables
- cleaned up the UI stuff that was bothering me
- slices are cleared when a connectivity query is made

Left to do: I need some help with the type errors (sorry, I just can't figure out what's going on this time around)

2022-02-14 19:57 UTC, JackWilb requested changes
I'm planning to give you a couple rounds of review. The first here will be higher level issues, and then I'll comment on specific code that might be updated in the next round. 

Here are a few other things I noticed:

- I can't see a tooltip
- It was unintuitive to me that some of the slices were orange and some were not when I first made a network. The tooltip will help with this, but is there some other way we can show what the orange represents?
- There isn't enough padding on the "Edge Slices" at the top of the vis
- It looks like the SVG you added could be smaller from some playing around. I think 30px high would make it fit in a bit more. Unless I missed something that goes below each of the bars.
- I found it unintuitive that there were separate variables for start and end. Looking at your screenshot, it seems a bit more clear, but why would we want it across 2 variables? Is that something we could hide unless the user asks for it, knowing that `end variable` is a separate column in their data?
- There should be a button somewhere that will clean all the edge slicing away. It seems that the best way to do that currently is to remove the variables from the panel and re-run the slicing, but that's too much work for a user. If it's one button to clear, that will be much nicer.
- We should open an issue to make sure that the sorting we implement is able to take information from slices instead of the whole network
- Is there a nice way we can show what ranges of values fall into each time slice?

2022-02-14 19:57 UTC, JackWilb commented on src/components/ConnectivityQuery.vue
> +            store.commit.setSlicedNetwork([]);
Maybe this should just be a part of `updateNetwork`? It seems that every time it updates, we'd want to unset this

2022-02-17 22:56 UTC, gotdairyya commented
Date + Time View:
![image](https://user-images.githubusercontent.com/8480871/154584790-d22cafb3-161d-419b-9c58-6ff89914f42d.png)

Numeric + Time View:
![image](https://user-images.githubusercontent.com/8480871/154584906-4f87c26f-6ae0-47bf-92d1-984eda8940c8.png)

Numeric View:
![image](https://user-images.githubusercontent.com/8480871/154584879-969b1f40-092a-461b-83a4-feff4c0f1d7d.png)

Categorical View:
![image](https://user-images.githubusercontent.com/8480871/154585285-efed1a35-710b-480a-91c7-6a3e52882ec8.png)

2022-02-18 01:06 UTC, JackWilb requested changes
Looking good so far! I have a smaller round of changes here that will just help with some papercuts

2022-02-18 01:06 UTC, JackWilb commented on src/components/EdgeSlicing.vue
> +    function sliceNetwork() {
This fails silently if the range specified by user is outside of the values of the data. For example, I have data from 0 to 31 and if I specify -100 to 31, it fails without alerting the user. We could have some simple validation and show errors to the user when it happens

2022-02-18 02:09 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +            store.commit.setNetworkOnLoad(aqlNetwork);
Done

2022-02-18 02:09 UTC, gotdairyya commented on src/components/EdgeSlicing.vue
> +              <v-btn
Done

2022-02-18 02:25 UTC, gotdairyya commented on src/components/EdgeSlices.vue
> +    }
Issue #379

2022-02-18 02:28 UTC, gotdairyya commented on src/components/EdgeSlices.vue
> +    const svgWidth = computed(() => (currentInstance !== null ? currentInstance.proxy.$vuetify.breakpoint.width - store.state.controlsWidth : 0));
Issue #380

2022-02-18 02:30 UTC, gotdairyya commented on src/components/EdgeSlices.vue
> +    const timeExtent = computed(() => extent(Object.values(currentSlice.value.timeRanges).flat()));
Done

2022-02-18 20:31 UTC, gotdairyya commented on src/components/EdgeSlices.vue
> +    });
Done

2022-02-21 15:37 UTC, waxlamp commented on src/components/EdgeSlices.vue
> +      selectedArray.value[key] = true;
FWIW (might not apply here) you can use a "computed setter" (V2: https://v2.vuejs.org/v2/guide/computed.html#Computed-Setter) or a "writable computed" (V3: https://vuejs.org/guide/essentials/computed.html#writable-computed) to give semantics to "changing a value on a computed ref".

2022-03-09 00:07 UTC, gotdairyya commented on src/components/EdgeSlicing.vue
> +    function sliceNetwork() {
resolved for both number inputs _and_ date inputs

2022-03-09 00:14 UTC, gotdairyya commented on src/components/EdgeSlices.vue
> +      selectedArray.value[key] = true;
Ok, this has also been fixed!

2022-03-09 00:23 UTC, gotdairyya commented
As an overview, here is the expected views by data type.

**CATEGORICAL**
![image](https://user-images.githubusercontent.com/8480871/157348400-2dbad8ac-cae4-4d15-bfae-b76673e939ea.png)

**TIME BUT NOT DATE**
![image](https://user-images.githubusercontent.com/8480871/157348449-dc175a93-6e79-4f01-8c69-7e3d29fe7afd.png)

**TIME AND DATE**
![image](https://user-images.githubusercontent.com/8480871/157348498-b8da96cb-995e-46f2-90d0-b6c8841825ae.png)

2022-03-09 19:10 UTC, JackWilb approved these changes
Noticed a couple of small things, but in general, it's looking good to go!

2022-03-09 19:10 UTC, JackWilb commented on src/components/EdgeSlicing.vue
> +                :disabled="!isValidRange && !isDate && isNumeric"
Is this right? Shouldn't it be just `!isValidRange`? Why would we disable it if it's numeric?

2022-03-09 19:10 UTC, JackWilb commented on src/components/EdgeSlicing.vue
> +    // const dateFormatted: Ref<string[]> = ref([]);
Remnant

2022-03-09 19:27 UTC, gotdairyya commented on src/components/EdgeSlicing.vue
> +                :disabled="!isValidRange && !isDate && isNumeric"
This is so that the `isValidRange` only does the check for `isNumeric` selections. Otherwise, you can't slice along categories

2022-03-09 19:39 UTC, merged