Calc degrees
multinet-app/multimatrix pull request #389
Opened 2022-05-09 23:14 UTC by gotdairyya

### Does this PR close any open issues?
Closes #386 

### Give a longer description of what this PR addresses and why it's needed
Let's the user filter nodes based on the number of out degrees.

### Are there any additional TODOs before this PR is ready to go?
I'm sure the code will need some sprucing up. I'm not sure I computed the filtering in the best way.
TODOs:
- [ ] Review code for filtering

2022-05-10 16:53 UTC, gotdairyya commented
Also, @JackWilb I set the min and max attributes for the range-slider, but for some reason, they aren't limits (ex. if the min in 0, I can still input a value less than 0)

2022-05-10 17:31 UTC, JackWilb requested changes
Looking good. I pushed a change for the slider UI (which I think will address your most recent comment) and I left some comments for how you might improve the filtering. I also noticed some general stuff that it would be best to fix up. Let me know if you'd like me to help with any of it

2022-05-10 17:41 UTC, gotdairyya commented on src/store/index.ts
> +      commit.setDegreeRange([0, networkElements.nodes.length]);
I would normally agree but in my example network there is a node with no interactions for this specific dataset so by that metric (max degree) it would never show up

2022-05-10 17:47 UTC, gotdairyya commented on src/lib/utils.ts
> +  nodes.forEach((d) => d.degreeCount = new Set(d.neighbors).size);
> Is this how the degree count should work? If there are 100 edges between 2 people, they would have degree 1

Did I misinterpret what `d.neighbors` represents?


> Another issue is that we're tracking the same data in 2 different variables. It seems that degree count is just the size of the neighbors. Why don't we make neighbors a set or an object (to count edges, e.g. {"Jack": 10, "Derya": 20}), and then just use the size or length of keys instead of making a separate degreeCount variable?

Why would that be better? If it is a node variable then it will also show up in the UpSet table which could be useful.

2022-05-10 17:47 UTC, gotdairyya commented on src/components/Controls.vue
> +    const degreeMax = computed(() => (networkOnLoad.value !== null ? networkOnLoad.value.nodes.length : 0));
I will check

2022-05-10 17:48 UTC, gotdairyya commented on src/components/Controls.vue
> +          if (nodeDegreeDict[edge._from] < parseInt(degreeRange.value[0]) || nodeDegreeDict[edge._from] > parseInt(degreeRange.value[1])) {
`degreeRange` is typecast for `number[]` but when I was testing the code and console logging, sometimes it would return a string. I wasn't sure why it was doing that

2022-05-10 17:49 UTC, gotdairyya commented on src/components/Controls.vue
> +        const newNetwork = JSON.parse(JSON.stringify(networkOnLoad.value));
:thumbs_up:

2022-05-10 17:49 UTC, gotdairyya commented on src/components/Controls.vue
> +        for (let i = 0; i < newNetwork.edges.length; i++) {
oh that's much nicer, thank you!

2022-05-10 21:52 UTC, gotdairyya commented on src/components/Controls.vue
> +        for (let i = 0; i < newNetwork.edges.length; i++) {
done

2022-05-10 21:52 UTC, gotdairyya commented on src/components/Controls.vue
> +        for (let i = 0; i < newNetwork.nodes.length; i++) {
done

2022-05-16 21:24 UTC, gotdairyya commented on src/components/Controls.vue
> +        const newNetwork = JSON.parse(JSON.stringify(networkOnLoad.value));
Had to use `// eslint-disable-next-line no-undef`, tracking in issue #390

2022-05-16 22:47 UTC, gotdairyya commented
@JackWilb I've updated how the degrees are calculated. Could you help with the type setting? And it should be good after that unless you notice anything else

2022-05-17 15:50 UTC, JackWilb commented on src/components/Controls.vue
> +      if (networkOnLoad.value != null) {
This is null on load for me, which causes the slider to initialize to [0,0]

2022-05-17 19:20 UTC, gotdairyya commented on src/components/Controls.vue
> +      if (networkOnLoad.value != null) {
I think I fixed this

2022-05-17 20:44 UTC, JackWilb commented on src/components/Controls.vue
> +      if (networkOnLoad.value != null) {
It seems so!

2022-05-17 20:56 UTC, JackWilb commented on src/lib/utils.ts
> +  nodes.forEach((d) => d.degreeCount = new Set(d.neighbors).size);
Derya showed me that this is a bad idea. We've pivoted a bit from this

2022-05-17 21:21 UTC, JackWilb requested changes
This code is looking pretty good so far. I have a couple of suggestions in the comments, but the ones about the computed vs a ref with a watcher might not work.

On another note, the node degree filtering doesn't work with an aggregated network. It also doesn't work with quering, since it just copies networkOnLoad, which is not updated. I'm not sure the best way to make all of this work with that 😅 but maybe it will become obvious as you play some more with it... If not, I'm happy to dig in and see what I can see for simplifying it all

2022-05-17 21:21 UTC, JackWilb commented on src/store/index.ts
> +        state.networkOnLoad.nodes.forEach((node) => {
Should this be `networkOnLoad`? If we make it `network`, then it might work better with aggregation, etc. We'd just make sure we call it on load and when aggregating.

2022-05-17 21:21 UTC, JackWilb commented on src/store/index.ts
> +          if (state.nodeDegreeDict[edge._from] >= degreeRange[0] && state.nodeDegreeDict[edge._from] <= degreeRange[1]) {
This gives us all out edges from nodes that are in the degree range (and all their neighbors). Should we also allow all in edges (especially in the case that we don't care about edge directionality)?

2022-05-17 21:21 UTC, JackWilb commented on src/store/index.ts
> +          if (state.nodeDegreeDict[edge._from] >= degreeRange[0] && state.nodeDegreeDict[edge._from] <= degreeRange[1]) {
Also, should we include their neighbors or only include them if they are also in the degree range?

2022-05-17 21:21 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +            const nodes = defineNeighbors(aqlNetwork.nodes, aqlNetwork.edges as Edge[]);
It feels weird to have the `defineNeighbors` step here. I think this should just be in the store in the update network function. Let me know what you think about that

2022-05-17 21:21 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +            store.dispatch.updateNetwork({ network: aqlNetworkElements });
If you accept the other change in this file, these will need to be switched and you'll need to pass another network to `setNetworkOnLoad`
```suggestion
            store.dispatch.updateNetwork({ network: aqlNetworkElements });
            store.commit.setNetworkOnLoad(store.state.network);
```

2022-05-17 21:21 UTC, JackWilb commented on src/components/Controls.vue
> +    });
Can this be made into a computed? I'm not sure if this will have issues with reactivity. It could also cause issues with the value in the html below.

```suggestion
    const degreeRange = computed(() => [0, maxDegree.value]);
```

2022-05-17 21:21 UTC, JackWilb commented on src/components/Controls.vue
> +              v-model="degreeRange"
I wonder if this `v-model` is needed if you switch to using a computed.

2022-05-19 23:09 UTC, gotdairyya commented on src/store/index.ts
> +        state.networkOnLoad.nodes.forEach((node) => {
we want it to be `networkOnLoad` because the filtering updates the `network` and that's how the matrix is redrawn. I can check for aggregation and change the network that is used (same for querying). 

If you have another idea for how to redraw the matrix without updating the network that would be great.

2022-05-19 23:10 UTC, gotdairyya commented on src/store/index.ts
> +          if (state.nodeDegreeDict[edge._from] >= degreeRange[0] && state.nodeDegreeDict[edge._from] <= degreeRange[1]) {
> This gives us all out edges from nodes that are in the degree range (and all their neighbors). Should we also allow all in edges (especially in the case that we don't care about edge directionality)?

Oh, yeah I can do that based on whether it is a directional matrix or not

- [ ] Account for directionality in filtering

2022-05-19 23:11 UTC, gotdairyya commented on src/store/index.ts
> +          if (state.nodeDegreeDict[edge._from] >= degreeRange[0] && state.nodeDegreeDict[edge._from] <= degreeRange[1]) {
> Also, should we include their neighbors or only include them if they are also in the degree range?

I don't understand this, sorry

2022-05-19 23:12 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +            const nodes = defineNeighbors(aqlNetwork.nodes, aqlNetwork.edges as Edge[]);
I don't think so! It is another source of creating new network data which I see as equivalent to when smaller networks are loaded

2022-05-19 23:14 UTC, gotdairyya commented on src/components/FilterOverlay.vue
> +            const nodes = defineNeighbors(aqlNetwork.nodes, aqlNetwork.edges as Edge[]);
> This code is looking pretty good so far. I have a couple of suggestions in the comments, but the ones about the computed vs a ref with a watcher might not work.
> 
> On another note, the node degree filtering doesn't work with an aggregated network. It also doesn't work with quering, since it just copies networkOnLoad, which is not updated. I'm not sure the best way to make all of this work with that 😅 but maybe it will become obvious as you play some more with it... If not, I'm happy to dig in and see what I can see for simplifying it all

To Do:

- [ ] have filtering work on aggregated network
- [ ] have filtering work on queried network

2022-05-20 15:56 UTC, JackWilb commented on src/store/index.ts
> +          if (state.nodeDegreeDict[edge._from] >= degreeRange[0] && state.nodeDegreeDict[edge._from] <= degreeRange[1]) {
> > Also, should we include their neighbors or only include them if they are also in the degree range?
> 
> I don't understand this, sorry

You add both nodes to `nodeSet` when the from node has the right degree. That means the to node will get included. Is that what we want? Or should we just show the connections between all nodes that have the right degree?

That would change the logic to:
1. Filter the nodes to include only those in the degree range.
2. Find all edges that have from and to in the filtered nodes.

I guess I'm just wondering if we're doing this filtering step backwards as it's written

2022-05-20 15:58 UTC, JackWilb commented on src/components/FilterOverlay.vue
> +            const nodes = defineNeighbors(aqlNetwork.nodes, aqlNetwork.edges as Edge[]);
I wasn't very clear here. What I meant was, don't we want to redefine the neighbors each time we update a network? If so, it would make sense to do that in the store function that handles it. However, it could be that we don't want to do it every time, and that there's a good reason to do it here (I'm thinking aggregation)

2022-05-21 00:00 UTC, gotdairyya commented on src/store/index.ts
> +          if (state.nodeDegreeDict[edge._from] >= degreeRange[0] && state.nodeDegreeDict[edge._from] <= degreeRange[1]) {
So this is what I did at first and then I realized that we need to track the to nodes or else we may end up having an edge without an edge that is connected to and that will throw an error when the matrix is drawn.

2022-05-23 17:41 UTC, JackWilb commented on src/store/index.ts
> +          if (state.nodeDegreeDict[edge._from] >= degreeRange[0] && state.nodeDegreeDict[edge._from] <= degreeRange[1]) {
The edge should only be included if both the from and to are in the selected subset. That should fix that problem

2022-05-25 17:33 UTC, gotdairyya commented
@JackWilb I made quite a few changes so I will list them out here. I didn't make the ref to a computed, I had tried that and had some issues, if you can look at that that would be great.

**Major Changes:**
- Moved the computation of the node degree dict to the utils
- Added logic for directionality in the matrix
- Filtering works for any combination of aggregated network and/or queried network

2022-06-10 22:54 UTC, gotdairyya commented
Jack and I decided to go ahead and disable degree filtering when aggregating the network because both of these methods are meant to make the network smaller. It also removes visual complexity.

**Left to do:**
- [ ] Fix color for filtered children cells
- [ ] Reset rangeSlider when aggregating
- [ ] Remove filtered nodes from aggregation function
- [ ] Check if new design works with queried network (or @JackWilb do we disable it here too)

2022-06-13 15:16 UTC, JackWilb commented
> Remove filtered nodes from aggregation function

We could probably reset the network before aggregation

> Check if new design works with queried network (or @JackWilb do we disable it here too)

Querying should reset everything, and give you the queried network

2022-06-29 17:32 UTC, JackWilb submitted a review, later dismissed
Looks good! I have a couple of suggestions for you to fix up before you merge. It should simplify some checks and remove some duplicated code

2022-06-29 22:36 UTC, gotdairyya commented on src/components/Controls.vue
> +        if (networkOnLoad.value !== null) { store.dispatch.updateNetwork({ network: networkOnLoad.value }); }
Done

2022-06-29 22:39 UTC, gotdairyya commented on src/lib/utils.ts
> +  if (baseNetwork !== null) {
done

2022-06-29 22:41 UTC, gotdairyya commented on src/store/index.ts
> +      let baseNetwork: Network | null = { nodes: [], edges: [] };
done

2022-06-29 22:45 UTC, gotdairyya commented on src/lib/utils.ts
> +        Object.prototype.hasOwnProperty.call(nodeDegreeDict, edge._from) ? nodeDegreeDict[edge._from] += 1 : nodeDegreeDict[edge._from] = 1;
Opened in issue #406

2022-06-29 23:02 UTC, JackWilb approved these changes

2022-06-29 23:02 UTC, merged